elk-zone/elk

- README.md
Based on https://twitter.com/nuxt_js/status/1613491322148605954, I'd say that sharing is fine now? 👀
> chore(readme): remove non-sharing hint

- README.md
> docs: fix elk screenshot on mobile

- components/content/ContentMentionGroup.vue
- components/status/StatusBody.vue
- composables/content-parse.ts
- composables/content-render.ts
- styles/global.css
- tests/content-rich.test.ts
Initial try. I personally would prefer to have an even less conspicuous design, like a smaller font size and gray text etc.
---
Before: 
After:
> feat: collapse mentions

- components/common/OfflineChecker.vue
- layouts/default.vue
> fix: offline checker not show in large screen

- components/common/CommonBlurhash.vue
resolves #1022 
Probably not the smart way... But I can't figure out any other way at the moment
> feat(ui): smoothly unblurring picture placeholders

- composables/users.ts
Fixes #1056
I'm new to Vue, could someone explain to me waht the `._` property actually is? I can't find any docs on it.
I fear this PR just papers over the cracks of the bug and doesn't solve the root cause.
> fix: handle undefined `._` property on `useUserLocalStorage`

- locales/fr-FR.json
- added missing key on block and mute
- change mutuals for Abonné·e·s instead of Suivi·e·s
- Revert Apprecier for Aimer
> fix(i18n): update french translation

- components/common/CommonInputImage.vue
- components/notification/NotificationEnablePushNotification.client.vue
- components/notification/NotificationPreferences.client.vue
- components/publish/PublishWidget.vue
- components/tiptap/TiptapHashtagList.vue
- components/tiptap/TiptapMentionList.vue
- components/user/UserSignIn.vue
- error.vue
- pages/settings/profile/appearance.vue
https://streamable.com/og19l7
Fix here: https://github.com/unocss/unocss/issues/300#issuecomment-1000886775
> fix: remove Firefox icon border when using animate-spin

- components/publish/PublishEmojiPicker.client.vue
- locales/en-US.json
- locales/es-ES.json
cc @patak-dev @userquin 
This PR also includes `tooltip.add_emojis` for `en_US`.
> feat(i18n): Sync es-ES and 'add emojis' tooltip localized.

- components/user/UserSignIn.vue
- server/api/[server]/login.ts
> fix: allow multiple accounts on same server

- locales/en-GB.json
- locales/en-US.json
- locales/nl-NL.json
[Discussed](https://discord.com/channels/1044887051155292200/1044887051155292203/1063393229434781697) in general channel on Discord, for the text in the Preview modal:
> To help boosting out development, you can sponsor the Team through GitHub Sponsors. We hope you enjoy Elk!
Seems there was general agreement from @patak-dev, @danielroe and me that:
To boost development, you can sponsor the Team through GitHub Sponsors. We hope you enjoy Elk!
…sounds better. Love the use of **boost** here btw! [:chef_kiss:](https://i0.kym-cdn.com/entries/icons/original/000/021/267/swedish_chef.jpg)
> chore: trim desc_para3 open, help boosting out to boost

- composables/tiptap/suggestion.ts
Closes #898 
https://user-images.githubusercontent.com/22515951/212467876-32bc358a-8364-4537-9e25-87648a6023e8.mov
https://user-images.githubusercontent.com/22515951/212467888-e61daea4-a406-4693-bbf6-4ef242288643.mov
> fix: update suggestion renderer only when the editor is focused

- pages/settings/profile/appearance.vue
> chore: add cursor pointer for checkbox

- pages/[[server]]/@[account]/index/followers.vue
Signed-off-by: Innei <tukon479@gmail.com>
> fix: [object Object] in page title of followers page #1151

- locales/en-US.json
- locales/zh-CN.json
- locales/zh-TW.json
- pages/compose.vue
Add page title for compose page
---
> feat: add page title for compose page

- .github/PULL_REQUEST_TEMPLATE.md
> chore: update pr template [skip ci]

- components/user/UserDropdown.vue
> fix: make user dropdown to be fixed

- locales/zh-TW.json
> fix(i18n): update zh-TW translations

- plugins/social.server.ts
> refactor: use internal nuxt helper

- pages/[[server]]/@[account]/[status].vue
Be related to #1163 ,Closes #988 
---
> fix: show status actions on DM

- docs/app.vue
- docs/tokens.config.ts
- styles/global.css
- unocss.config.ts
#1190
https://github.com/elk-zone/elk/pull/1182#issuecomment-1383225179
---
> refactor: remove unused DM Sans

- components/publish/PublishWidget.vue
> fix: reply button on right on small screen

- components/status/StatusAttachment.vue
text for media
fixes: Alt text no longer wraps #1181
> fix: Swap whitespace-pre for whitespace-pre-wrap on alt

- composables/masto/notification.ts
because we were awaiting a promise in `connect`, it was possible to have multiple streams pushing notifications to the queue. this fixes that by initialising it with an 'inside-out' promise.
---
> fix: initialise stream promise before stream is available

- README.md
add universeodon.com as public client
> docs: add universeodon.com as public client

- components/account/AccountFollowButton.vue
- locales/en-US.json
- locales/zh-CN.json
- locales/zh-TW.json
> feat: confirm before unfollow

- README.md
I am note sure if it might sound too discouraging but I do concern about this.
> docs: note about the risk for 3rd-party deployments

- components/account/AccountMoreButton.vue
- components/modal/ModalConfirm.vue
- components/status/StatusActionsMore.vue
- locales/ar-EG.json
- locales/de-DE.json
- locales/en-US.json
- locales/es-ES.json
- locales/fr-FR.json
- locales/pt-PT.json
- locales/tr-TR.json
- locales/uk-UA.json
- locales/zh-CN.json
- locales/zh-TW.json
> refactor(i18n): confirm module

- locales/ja-JP.json
Because of the recent active development, many texts lack Japanese translation now. This PR adds/updates these missing Japanese localization.
**Before**
**After**
Although there are small changes, the current Japanese localization is mostly done by the initial submission #228 (created on Nov 29, 2022).
---
> feat(i18n): Update Japanese localization

- components/status/StatusActionsMore.vue
- components/status/StatusBody.vue
- components/status/StatusContent.vue
- components/status/StatusTranslation.vue
- composables/masto/translate.ts
- nuxt.config.ts
closes #1118 
- move `translate` to end of contents
- improve `translation` logic, improve error handling
Error cause I dont have this service. 😅 
https://user-images.githubusercontent.com/49969959/212620719-1f180183-c58a-4c07-bf99-7f9bf0d1ccc7.mp4
BTW, I don't know why I can't use [onRequestError](https://github.com/unjs/ofetch#onrequesterror-request-options-error-) in `nitro`, It cannot reached.
---
> feat: improve posts translation logic

- locales/en-GB.json
- locales/en-US.json
Came accross this popup today. I am still unable to enable push notifications, but at least with this change the error will look nicer.
I switched accounts recently, and tried unsubscribing to push notifications from Elk beforehand, but still, I get that popup… not sure what to try.
---
> chore: typo

- components/account/AccountAvatar.vue
- components/account/AccountInfo.vue
- components/common/dropdown/DropdownItem.vue
In general, the UI which is clickable should be disabled selecting. So I apply `select-none` to some components.
---
[resolves](https://github.com/elk-zone/elk/pull/1147#pullrequestreview-1249270527)
> fix: disable selecting elements in user switcher

- .dockerignore
- Dockerfile
So it would be easier to deploy
> feat: add docker support

- components/status/StatusPoll.vue
> chore: add cursor pointer for input element

- Dockerfile
- docker-compose.yaml
Add docker-compose support
How to test it ?
- clone my branch
- make sure you've installed [`docker-compose`](https://docs.docker.com/compose/)
- in root path, execute `sudo docker compose up --build`, you will see logs print in your terminal.
---
> feat: add docker-compose support

- README.md
Adds [elk.vmst.io](https://elk.vmst.io) to the list of community instances.
---
- X Documentation update
- X Read the [Contributing Guidelines](https://github.com/elk-zone/elk/blob/main/CONTRIBUTING.md).
- X Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- X Provide related snapshots or videos.
- X Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
> docs: add vmst.io to community instances

- locales/ar-EG.json
I fixed some words to be more coherent for the Arab users 
If there is a conflict or a missing comma
---
> fix(i18n): update Arabic

- locales/nl-NL.json
Noticed some missing translations, grammar / spelling mistakes / odd translations and fixed to my best efforts
---
> fix(i18n): improve several translations nl-NL

- components/common/CommonMask.vue
- components/user/UserDropdown.vue
- composables/mask.ts
Closes #718 #1238 
If this solution works, I'll apply it to all contexts that use dropdown.
https://user-images.githubusercontent.com/22515951/213072037-382b28f2-6a19-448f-ac78-5d3147b75d42.mov
https://user-images.githubusercontent.com/22515951/213072053-885d6050-c769-478f-bff6-a52e1476b146.mov
---
> fix: prevent default event when hide dropdown

- components/publish/PublishWidgetFull.client.vue
> fix: arrow placement in draft dropdown

- locales/id-ID.json
Hello everyone, this time there is a refinement of my previous translation. I used words that are more familiar and easy to understand. And there are new translations added. 
Thank you
- Translation improvement
- New translation
---
> feat(i18n): Improvements for Indonesian translation

- components/account/AccountHeader.vue
e.g. Twitter
https://user-images.githubusercontent.com/22515951/213364829-1feac29e-df88-4770-97dd-0fc6b97a5a49.mov
https://user-images.githubusercontent.com/22515951/213365146-25525178-cc68-4e3f-b756-ecbf70ba11a5.mov
---
> chore: preview header only when it's already set

- package.json
- pages/settings/profile/appearance.vue
- pnpm-lock.yaml
> chore: update slimeform

- components/account/AccountHandle.vue
> fix: user server name getting clipped

- locales/fr-FR.json
> feat(i18n): french translation of updater + auto play

- locales/pt-PT.json
This updates the portuguese from Portugal translation.
---
> fix(i18n): Update portuguese from Portugal translation

- components/nav/NavLogo.vue
Opened to help to get feedback for the logo.
Down stream into #1328 if approved.
> style: colorize antlers only

- .github/workflows/docker.yml
This merge request adds a build & push action to ghcr, the github container registry which is free for open source projets.
It will build a `ghcr.io/elk-zone/elk:<tag-name>` container for every newly created tags, and a `ghcr.io/elk-zone/elk:main` will be built every time a commit is added on main.
> feat: add docker build & push to ghcr action

- Dockerfile
This merge request adds an extra layer of security, by running elk with an unprivileged user
> feat(docker): run as non root user

- config/i18n.ts
- locales/de-DE.json
- locales/fi-FI.json
This is courtesy of [Martin Vermeer](https://fediscience.org/@martinvermeer). Thank you! ❤️
> feat: add finnish locale

- components/status/StatusCard.vue
> fix: remove whitespace wrapping on status aside

- CONTRIBUTING.md
- config/i18n.ts
there will be no way to solve this ;)
> chore(i18n): move country variants to avoid changing contributing guide

- components/main/MainContent.vue
- components/pwa/PwaInstallPrompt.client.vue
- components/pwa/PwaPrompt.client.vue
- layouts/default.vue
- locales/en.json
- locales/es.json
- locales/fr-FR.json
- plugins/pwa.client.ts
This PR also changes dark icon color, too dark on update prompt.
supersedes #1304
> feat(pwa): add install PWA widget

- locales/fi-FI.json
ref #1379 which I found to be of pretty bad quality (sorry to original author)
> Revised Finnish localization

- locales/es.json
> feat(i18n): sync base `es`

- composables/masto/publish.ts
> fix: prevent click event when publish button is disabled

- README.md
added freelancers.online and cupoftea.social to the ecosystem
> docs: add new elk instances

- components/status/StatusAttachment.vue
- locales/en.json
> feat(i18n): locales for alt text

- locales/en.json
> fix(i18n): add `the` in delete

- composables/setups.ts
> fix(ui): add viewport header to enable/disable pinch to zoom in Safari

- components/list/Account.vue
- components/list/ListEntry.vue
> fix(lists): focus lost when focusing buttons

- components/account/AccountFollowButton.vue
- locales/en.json
> feat: introduce "request to follow" closes #1076

- components/main/MainContent.vue
- components/nav/NavSide.vue
- components/nav/NavTitle.vue
- layouts/default.vue
- Revamp the padding around logo
- make the logo sticky in case of small height screen
- Add more global native grab attribute to let user to grap from more empty space
> fix: make nav title sticky + add more grabbale area for native

- middleware/auth.ts
> fix: sign-out and empty content

- modules/pwa/index.ts
- nuxt.config.ts
Should fix: https://elk.zone/mastodon.social/@ironicsans/109806735051868561
> fix(pwa): configure sw and web manifest cache control headers

- components/nav/NavBottom.vue
| Before | After |
| - | - |
| ![Screen Shot 2023-02-12 at 01 38 06](https://user-images.githubusercontent.com/28706372/218287191-eb7908d0-2c54-4bb8-9682-7918d86c3c1e.png) | ![Screen Shot 2023-02-12 at 01 38 00](https://user-images.githubusercontent.com/28706372/218287193-2611b8c8-6032-444c-8d65-bbf50a39c04e.png) |
> fix: add badge to bottom bar notifications icon

- components/publish/PublishWidget.vue
- composables/masto/statusDrafts.ts
This PR reverts #1699, we cannot start compsing with a mention, it is removed from the editor
> fix: revert #1699

- components/settings/SettingsTranslations.vue
> fix(ui): fix button width shrinked

- composables/masto/statusDrafts.ts
> fix: do not overwrite status drafts

- page-lifecycle.d.ts
- plugins/page-lifecycle.client.ts
> fix: handle frozen state

- README.md
[X] Add elk.fedified.com to list of publicly-accessible servers
> docs: Add elk.fedified.com to ecosystem list

- composables/content-parse.ts
Fixes https://github.com/elk-zone/elk/issues/1869
> fix: get custom emoji id from title attribute

- locales/zh-CN.json
/cc @elk-zone/translators-zh-cn
> feat(i18n): sync zh-CN with en

- components/account/AccountHeader.vue
- components/account/AccountMoreButton.vue
- locales/en.json
Requested by [@bebatjof@strangeobject.space](https://elk.zone/toot.community/@bebatjof@strangeobject.space/110130984392497080).
[Screencast from 2023-04-09 17-55-52.webm](https://user-images.githubusercontent.com/24935987/230783190-f51161e6-3674-4bfa-a640-88635d2bf072.webm)
> feat: personal notes

- components/account/AccountHoverWrapper.vue
> fix: wrong profile showing on hover sometimes (#1913)

- config/i18n.ts
- locales/ko-KR.json
> feat(i18n): add Korean translation

- components/account/AccountHeader.vue
The basic `textarea` for the personal notes did not change its height to fit the content.
I made it do this now, but I had to hack it into doing it a bit. The `textarea` tag doesn't listen to you telling it to have its height fit the content, so here's what I did:
I wrapped the `textarea` in a parent div, and gave the `textarea` a sibling `div` that contains the same content as the textarea. This `div` **can** be told to set its height based on its content.
I made the `textarea` absolutely positioned and scaled to be 100% its parent's height.
This parent's height would fit its content which is, because the `textarea` is absolutely positioned, just the sibling `div`.
The result is that the textarea is the height it needs to be.
> feat: improve personal notes

- locales/eu-ES.json
Added missing strings:
- "profile_personal_note"
- "add_personal_note"
- "remove_personal_note"
Improved:
- "help.title"
> fix(i18n): update Basque localisation

- config/i18n.ts
- locales/it-IT.json
- locales/it.json
supersedes #1891
supersedes #1892
> feat(i18n): Add Italian Localisation

- components/account/AccountHeader.vue
> fix: Allow account handles to wrap in AccountHeader

- locales/it-IT.json
Corrected status/post ambiguities.
> feat(i18n): Update it-IT locale

- composables/masto/statusDrafts.ts
> fix: reply remove-and-re-draft error

- components/common/CommonRouteTabs.vue
- composables/settings/definition.ts
- locales/en.json
- locales/zh-CN.json
- pages/[[server]]/explore.vue
- pages/settings/preferences/index.vue
> feat: add wellbeing preference hide news

- components/settings/SettingsColorMode.vue
This pull request involves a code refactoring that simplifies the process of creating and designing buttons by replacing redundant code with a more streamlined implementation using a v-for loop. This change reduces code redundancy and makes the code more efficient 🌻
> refactor: button creation with v-for to remove redundancy

- docs/nuxt.config.ts
- docs/package.json
- nuxt.config.ts
- package.json
- pnpm-lock.yaml
After updating version constraints in `package.json`, I ran:
```sh
pnpm up -rL nuxt
pnpm dedupe
```
> chore: upgrade to nuxt v3.4.3

- components/modal/ModalMediaPreviewCarousel.vue
> fix: image preview should justify-center

- locales/fr-FR.json
Let's switch `État de la traduction : 455/482 (94.4 %)` to `État de la traduction : 482/482 (100 %)` 🙂
> feat(i18n): Update fr-FR locale

- locales/nl-NL.json
After being called out https://elk.zone/phpc.social/@elk@webtoo.ls/110303749190747263  😅 
Some of these translations might be a little contentious, open for feedback (or dropping this PR).
> fix(i18n): Updated nl-NL.json

- components/nav/NavBottom.vue
- components/nav/NavSide.vue
- pages/[[server]]/explore.vue
- pages/[[server]]/search.vue
Closes #2064
Closes #1704
See @TodePond post for reference https://github.com/elk-zone/elk/pull/1301#issuecomment-1416490216
Partial revert of #1301
@shuuji3 it was easier to do the revert, please test this one. Thanks!
> feat: separate search and explore

- components/status/StatusContent.vue
@patak-dev expoiler text length was wrong in my previous PR
> fix(ui): check empty spoiler text

- README.md
> docs: Update README.md to fix typo

- locales/tr-TR.json
> fix(i18n): update tr-TR translations

- components/publish/PublishWidget.vue
- composables/masto/publish.ts
- locales/en.json
> feat: adhere to and display poll limits

- config/i18n.ts
- locales/vi-VN.json
> feat(i18n): Add Vietnamese locale

- locales/vi-VN.json
I fixed some context errors after trying it out canary version
> feat(i18n): Update vi-VN.json

- locales/eu-ES.json
Added new strings:
- common.no_bookmarks
- common.no_favourites
- settings.preferences.hide_news
- settings.preferences.zen_mode
- settings.preferences.zen_mode_description
- status.account.suspended_message
- status.account.suspended_show
- notification.reported
- settings.preferences.use_star_favorite_icon
- status.spoiler_media_hidden
Improved:
- settings.preferences.hide_follower_count
Removed:
- magic_keys.groups.actions.zen_mode
> fix(i18n): update eu-ES.json

- components/account/AccountPostsFollowers.vue
https://glitch-soc.github.io/docs/features/hide-follower-count/
> fix: handle hidden followers/following count

- package.json
- pnpm-lock.yaml
Also updated workbox-build and workbox-window to 7.0.0
> chore: bump to vite-plugin-pwa 0.16.0

- components/status/StatusPoll.vue
> fix(ui): do not show poll expiration if missing

- README.md
Adding another server to spread the word about the ELK Project :)
> docs: add bolha.us server to readme

- locales/de-DE.json
Just an addition of missing German translations using ChatGPT, reviewed manually.
> fix(i18n): add missing translations for de-DE

- pages/[[server]]/@[account]/[status].vue
Fix for #2193
Adding a `key` attribute to the StatusCard seems to fix the issue.
> fix: status card confusion

- middleware/auth.ts
- modules/pwa/i18n.ts
This PR fixes notifications and local PWA installed shortcuts.
> fix: installed pwa shortcuts

- components/publish/PublishWidget.vue
> fix(ui): stop question mark propagation

- .github/renovate.json5
> chore(renovate): ignore node version correctly

- locales/en.json
- pages/settings/preferences/index.vue
fix #1142
As suggested by issue https://github.com/elk-zone/elk/issues/1142, just added descriptions to the current three experimental features available on preferences page.
I've seen that this PR https://github.com/elk-zone/elk/pull/1239 didn't had any updates in months so I've decided to create a new one based on those translations.
> feat: add experimental features descriptions

- locales/en.json
- locales/fr-FR.json
Hey, added some french translations where it was missing. 🙂
Before: `fr-FR 90.8% (483/532)`
After: `fr-FR 100% (532/532)`
> feat(i18n): Update the fr-FR locale

- components/notification/NotificationGroupedLikes.vue
> fix: Use favorite star icon in notifications when enabled

- locales/zh-CN.json
> feat(i18n): Update zh-CN locale

- components/nav/NavBottomMoreMenu.vue
> fix: nav more menu not active

- locales/ko-KR.json
> fix(i18n): Improve Korean translation

- locales/es.json
> feat(i18n): Add missing Spanish translations

- components/publish/PublishWidget.vue
> fix: shrink the height of avatar

- components/publish/PublishWidget.vue
Without this PR refreshing compose page using Polsky (for example) fails (using en, or any es variant works !).
closes #2273
> fix: compose page error

- config/i18n.ts
- locales/fi-FI.json
Added all the missing strings and improved the existing ones.
> feat(i18n): update and improve Finnish locale

- locales/ko-KR.json
Fixed typos and made the translation more natural.
> fix(i18n): fix Korean translation

- locales/vi-VN.json
> fix(i18n): Update vi-VN.json

- components/magickeys/MagickeysKeyboardShortcuts.vue
- locales/en.json
- locales/ja-JP.json
resolve #2420
This adds the "Search" item under the "Actions" group.
> feat(ui): add "search" to the keyboard shortcut help

- locales/id-ID.json
Done 100%, I've tried it locally, with run `PWA`.
I've checked, maybe if there is time in the future there will be a slight improvement in the wording I will revise. because I am an Indonesian citizen.
> feat(i18n): Update the id-ID locale

- locales/ar.json
Updated the arabic locale to match the latest english locale
> feat(i18n): Update arabic locale

- styles/vars.css
This PR attempts to change the button color for better contrast and readability.
See this comment https://github.com/elk-zone/elk/issues/1365#issuecomment-1778542677 for the details.
**Screenshots**
> feat(a11y): improve button color contrast with white text

- composables/masto/icons.ts
- locales/id-ID.json
Added new keywords `548/551` to `551/551`. Revise `untranslated` words and revise `some` words.
> feat(i18n): Update id-ID locale

- nuxt.config.ts
This fixes media iframes not allowing outside sources :)
test post: https://deploy-preview-2468--elk-zone.netlify.app/universeodon.com/@elkdev/111394447159078784
> feat: allow https as frame-src

- package.json
- pnpm-lock.yaml
fixes a couple of bugs, particularly one which hid test output with some verbose (and irrelevant warnings)
> chore: bump `@nuxtjs/color-mode`

- locales/hu-HU.json
Translation status: 553/553 (100%)
> feat(i18n): hu-HU.json update 

- locales/es-419.json
- locales/es.json
> feat(i18n): es & es-419 locales sync

- .gitignore
- components/emoji/Emoji.vue
- composables/content-render.ts
- package.json
- pnpm-lock.yaml
- tests/nuxt/__snapshots__/content-rich.test.ts.snap
Show tooltip on hover over emoji
> feat: show emoji tooltip

- components/common/CommonPaginator.vue
- components/notification/NotificationPaginator.vue
- components/timeline/TimelineNotifications.vue
- composables/paginator.ts
Fixes #2554
Regression introduced by 
- https://github.com/elk-zone/elk/pull/2530
> fix: subscribe to proper user.notification stream

- locales/es.json
This PR includes the following missing keys:
- title for confirm dialogs
- low performance device
- lock account
/cc @patak-dev 
/cc @mrcego
> feat(i18n): Update es.json

- components/common/CommonRouteTabs.vue
- components/common/CommonTabs.vue
HelpPreview tabindex in another PR
> fix(ui): wrong tabindex usage

- components/status/StatusCard.vue
> fix(ui): missing replying to links

- constants/index.ts
- modules/pwa/i18n.ts
- plugins/color-mode.ts
extract colors: [#2659](https://github.com/elk-zone/elk/pull/2659#issuecomment-1983641274)
> chore: extract bg and theme colors to constants

- locales/eu-ES.json
Added missing strings and updated/fixed some others.
> feat(i18n): update eu-ES.json

- locales/hu-HU.json
> feat(i18n): Update hu-HU.json

- components/status/StatusActions.vue
This PR updates the status action title for:
- boost
- favorite
- bookmark
closes #2716
> fix(ui): change status actions title

- CONTRIBUTING.md
- components/common/CommonTabs.vue
- components/modal/ModalMediaPreviewCarousel.vue
- components/notification/NotificationPaginator.vue
- composables/content-parse.ts
- docs/README.md
- docs/components/global/ToggleIcon.vue
- docs/components/global/TranslationState.vue
- docs/content/2.deployment/1.netlify.md
- service-worker/notification.ts
I found several small typos and grammar errors with the help of the editor's code analysis feature across the project.
> refactor: various typo fixes

- locales/en.json
- pages/settings/about/index.vue
This is follow-up of https://github.com/elk-zone/elk/pull/2733#issuecomment-2029107029
(highlighting is because of mouse hovering)
🖼️ Page preview: https://deploy-preview-2734--elk-zone.netlify.app/settings/about
> feat: add "Documentation" link to "About" page

- components/settings/SettingsItem.vue
check https://github.com/elk-zone/elk/pull/2741#issuecomment-2030549227
> fix(ui): don't scroll on settings item click when external or `_blank` target  link

- locales/es.json
> feat(i18n): add missing spanish translations (gifs, docs and contributing)

- components/publish/PublishWidget.vue
- components/status/StatusContent.vue
> fix: adjust background spacing in direct message

- locales/hu-HU.json
> feat(i18n): update hu-HU.json - review

- components/nav/NavBottom.vue
- components/nav/button/Explore.vue
- components/nav/button/Federated.vue
- components/nav/button/Home.vue
- components/nav/button/Local.vue
- components/nav/button/Mention.vue
- components/nav/button/MoreMenu.vue
- components/nav/button/Notification.vue
- components/nav/button/Search.vue
- components/settings/SettingsBottomNav.vue
- composables/settings/definition.ts
- constants/index.ts
- locales/en.json
- pages/settings/interface/index.vue
> feat: allow choosing favorite buttons in bottom navigation bar

- locales/es.json
> feat(i18n): add spanish bottom navigation translations

- locales/pt.json
> feat(i18n): Update portuguese from Portugal translation

- locales/en-GB.json
> feat(i18n): update en-GB.json

- locales/pt.json
> feat(i18n): Update pt-PT language

- locales/es.json
This PR also fix errata in `list.edit` entry.
/cc  @patak-dev @mrcego
> feat(i18n): add `manage lists` spanish translation

- components/account/AccountMoreButton.vue
- components/help/HelpPreview.vue
- components/modal/ModalMediaPreview.vue
- components/nav/button/MoreMenu.vue
- components/report/ReportModal.vue
- components/status/StatusAttachment.vue
- components/user/UserPicker.vue
- components/user/UserSwitcher.vue
- locales/en.json
- There are several `aria-label` strings remaining only English
- The "Next" and "Previous" in the `aria-label` string were reversed
> fix(i18n,a11y): fix missing or incorrect translations in `aria-label` strings

- locales/pt.json
> feat(i18n): update pt-PT translation

- package.json
- pnpm-lock.yaml
> chore(deps): Update masto.js

- locales/tr-TR.json
> fix(i18n): Update tr-TR.json

- nuxt.config.ts
Add wideLayout property to PageMeta interface in nuxt.config.ts
> feat: add custom metadata type for PageMeta

- locales/ja-JP.json
- 4d83a2061980f935caf859a1edc71e7e8f4cc499: Some redundancies in the Japanese translation have been corrected.
> fix(i18n): Fix redundant Japanese translation

- components/account/AccountBigCard.vue
- components/command/CommandItem.vue
- components/common/CommonAlert.vue
- components/common/CommonCropImage.vue
- components/common/CommonInputImage.vue
- components/common/CommonTrending.vue
- components/common/CommonTrendingCharts.vue
- components/list/Lists.vue
- components/modal/ModalDialog.vue
- components/nav/NavBottomMoreMenu.vue
- components/nav/NavUser.vue
- components/settings/SettingsFontSize.vue
- components/settings/SettingsItem.vue
- components/settings/SettingsLanguage.vue
- components/settings/SettingsTranslations.vue
- layouts/default.vue
- pages/[[server]]/explore/index.vue
- pages/[[server]]/explore/links.vue
- pages/[[server]]/explore/tags.vue
- pages/[[server]]/explore/users.vue
- pages/[[server]]/lists.vue
- pages/settings.vue
- pages/settings/profile/appearance.vue
- pages/settings/users/index.vue
- pages/share-target.vue
this is just a straight forward unification
> chore: unify script setup lang order

- components/modal/ModalContainer.vue
> fix(ui): composer dialog layout broken

- components/modal/ModalContainer.vue
From this comment:
https://github.com/elk-zone/elk/pull/2955#issuecomment-2345826627
> chore: cleanup `ModalContainer.vue`

- composables/idb/index.ts
- composables/users.ts
- package.json
- plugins/0.setup-users.ts
- pnpm-lock.yaml
This PR also updates Nuxt Devtools to 1.5.0 (same problem solved by Anthony here https://github.com/nuxt/devtools/issues/723#issuecomment-2367603445)
/cc @danielroe @antfu 
closes #2935
> fix: top level await (chrome 129)

- package.json
- pages/notifications.vue
- pnpm-lock.yaml
> chore: update masto.js to latest version 6.10.1

- docs/app.config.ts
- docs/nuxt.config.ts
- docs/package.json
- package.json
- pnpm-lock.yaml
fix https://github.com/elk-zone/elk/issues/3042
> docs: fix documentation build error

- package.json
- pnpm-lock.yaml
upstreaming from https://github.com/nimbus-town/nimbus/pull/13
> chore: fix `@nuxt/schema` warning

- package.json
- pnpm-lock.yaml
> chore: update `consola` to 3.3.1

- components/publish/PublishWidget.vue
> fix: disable publish when be bypassed by Ctrl + Enter

- components/account/AccountHoverCard.vue
> fix: prevent infinite account hover card

- CONTRIBUTING.md
This is simply fixing one link.
> docs: fix broken link in CONTRIBUTING.md

- locales/tl-PH.json
This PR will add missing translations for Tagalog (tl-PH)
> feat(i18n): Update tl-PH locale

- locales/vi-VN.json
Localised new string and corrected one.
> feat(i18n): Update vi-VN locale

- locales/en.json
> chore: adjust unmute video setting wording

- locales/nl-NL.json
modify key status.img_alt.alt to status.img_alt.ALT
> feat: Update nl-NL.json uppercase key ALT

- components/list/Account.vue
- components/list/AccountSearchResult.vue
- components/list/Lists.vue
- components/search/SearchWidget.vue
- locales/en.json
- package.json
- pages/[[server]]/list/[list]/index/accounts.vue
- pnpm-lock.yaml
fix #1600 (included in list improvements #1586)
This implements a "Search among people you follow" field when viewing the Accounts in a list to easily add new accounts in the list being viewed.
https://github.com/user-attachments/assets/41afc7bb-9ded-45c7-9368-823e5b8a9c94
> feat: search for following when viewing accounts in a list

- components/status/StatusCard.vue
- components/timeline/TimelineHome.vue
- components/timeline/TimelinePaginator.vue
- components/timeline/TimelinePublic.vue
- components/timeline/TimelinePublicLocal.vue
- pages/[[server]]/tags/[tag].vue
fix #2636 
This will show a followed tag badge on a status
> feat: show followed hashtag badge
