elk-zone/elk

- composables/content-parse.ts
Fixes Elk freezing when rendering post that fails to render.
Demo of bug in video in this post: https://github.com/elk-zone/elk/issues/917#issuecomment-1380132738
This doesn't actually fix linked issue, but at least prevents Elk from freezing, so Elk can continue functioning and renders bad content as an empty string. It also logs error to console.
> fix: catch exceptions in HTML parser

- mocks/semver.ts
- nuxt.config.ts
this cuts 30kB of unused `semver` from the client-side bundle
> perf: mock semver import

- components/user/UserSignIn.vue
The `Pick you server and register` message is not highlighted. It does not look like a link and does not grab attention until hovered.
This PR highlights it by default.
> feat(ui): highlight pick you server message in sign in form

- components/common/CommonTrendingCharts.vue
Charts on the hashtags page are not shown because of the following error:
This issue does not occur in developer mode because of differences how default imports work when code with a `<script setup>` block is compiled and not
<details>
<summary>How it looks after (both in developer and production modes)</summary>
</details>
> fix: non-showing hashtag charts

- components/user/UserSignIn.vue
If the server list is empty in UserSignIn page, pressing up/down keyboard arrow throws console error. This PR fixes that.
> fix: empty server list throws console error on move

- modules/tauri/index.ts
- nuxt.config.ts
This PR:
1. Disables the PWA module for Tauri builds (since it's not needed anyway)
2. Cleans up files copied from the `public` folder that aren't needed in an app setting either
> chore: reduce bundle size for Tauri target

- locales/zh-CN.json
before: ![image](https://user-images.githubusercontent.com/73569598/212287982-ecc50d97-a626-432e-9cc2-43cd1063e4cc.png)
after: ![image](https://user-images.githubusercontent.com/73569598/212287938-cbec8a2c-799f-4dfb-88a1-e5d5fc1d8b42.png)
other
> fix(i18n): update zh-CN built_at translation for rationality

- components/notification/NotificationPreferences.client.vue
- composables/push-notifications/createPushSubscription.ts
- composables/push-notifications/types.ts
- locales/en-GB.json
- locales/en-US.json
- locales/es-ES.json
This PR doesn't solve the problem, just handle the error with a custom error message and the hint (we need to add push notifications proxy on Elk server, a lot of work to be done):
closes #999
> fix: multiple push notifications susbscriptions on multiple account servers

- components/main/MainContent.vue
When the page width is less than 1280 pixels and larger than 1024 pixels, the back button does not appear. 
Because the back button is set with the lg:hidden style inconsistent with the trigger width of sidebar shrinkage (sidebar shrinks at less than 1280px)
> fix: back button was not displayed on lg screen

- composables/shiki.ts
- composables/tiptap/shiki.ts
https://user-images.githubusercontent.com/22515951/212225502-5a68371a-3a5d-4d8c-b7d5-5378760f2b1c.mov
`Shiki` doesn't seem to provide highlighting for the text [language](https://github.com/shikijs/shiki/blob/main/docs/languages.md), we might be use markdown instead.
> fix: shiki fallback language

- components/account/AccountInlineInfo.vue
I see a small UI issue on avatar on avatar account name background:
> fix: adjust background of account name when it's a link

- composables/content-parse.ts
- styles/global.css
- tests/__snapshots__/content-rich.test.ts.snap
- tests/content-rich.test.ts
This only has effect if you are on a glitch (or other) instance that supports more html elements. (You can see this when logged out at http://localhost:5314/toot.cat/@woozle/109433157214171127.)
(I chose not to render `h1` larger as I thought it would mess with the aesthetic more than ol/ul.
resolves https://github.com/elk-zone/elk/issues/256
> feat: support additional html elements

- components/status/StatusDetails.vue
When use zen mode, all action panels are hidden except in status detail. Maybe it should have consistent performance.
before: 
after:
> fix: hide actions panel in status detail when use zen mode

- composables/cache.ts
we should not cache statuses by server alone - cache might include whether a user has liked the status which is user-specific. Saw a report in Discord to this effect.
Related issue but not resolved by this: https://github.com/elk-zone/elk/issues/1134.
> fix: use user id in cache key

- plugins/social.server.ts
Rather than return a response containing any information about a status/user/server, we can simply redirect to the correct URL of the mastodon instance involved. This instance's `robots.txt`, privacy policy, etc. will then govern the response. However, we still will get the benefit of whatever meta tags that instance provides.
**Discord**
**Twitter**
**Facebook**
**Elk**
**Mastodon UI**
resolves https://github.com/elk-zone/elk/issues/153
> feat: implement social previews by redirecting to origin server

- components/content/ContentCode.vue
- composables/shiki.ts
- tests/__snapshots__/content-rich.test.ts.snap
- tests/content-rich.test.ts
- vitest.config.ts
This pull request fixes a raw HTML injection vector. A Mastodon post payload that contains HTML that looks enough like a code block can bypass HTML sanitation. This is fixed by:
* not directly injecting unescaped HTML content in the ContentCode.vue component
* escaping code conten in shiki.ts when the requested language is not found or has not been loaded yet
Visiting the page https://elk.zone/bob.pwniverse.io/@jviide/109692653165280776 demonstrates how a message crafted on a normal, non-attacker-controlled instance (running the [Mastodon Glitch Edition](https://glitch-soc.github.io/docs/)) can paint over the whole Elk UI and run arbitrary code in e.g. click handlers.
There are two points of code that must be protected. The first one is the ContentCode.vue component. If the language is …
> fix: prevent HTML injections to code blocks

- plugins/social.server.ts
This catches a few more bots for redirecting direct access to server URLs
---
> fix: catch more bots with redirects

- public-staging/robots.txt
- public/robots.txt
This explicitly disallows pages that require auth from being crawled. The server routes should all be redirected following https://github.com/elk-zone/elk/pull/1144, which means once search engines update, we should only have one page indexed.
https://duckduckgo.com/?t=ffab&q=site%3Amain.elk.zone&ia=web
https://duckduckgo.com/?t=ffab&q=site%3Aelk.zone&ia=web
---
> fix: disallow all indexing on canary site and indexing of auth-only pages in prod

- nuxt.config.ts
- package.json
- pnpm-lock.yaml
proposal: It makes sense to help new contributors quickly find and open the `Vue SFC`.If it's unnecessary, just close the PR directly, thanks.
https://user-images.githubusercontent.com/22515951/212470109-bd6d977d-4e51-4b0f-b0a6-fb0cbe39cbdc.mov
It disabled by default, we can toggle it via:
> feat: add unplugin-vue-inspector

- components/common/CommonTooltip.vue
> fix: should hide tooltip when click outside

- pages/[[server]]/@[account]/[status].vue
- pages/[[server]]/@[account]/index.vue
- pages/[[server]]/tags/[tag].vue
Fetching a lstatus with many replies can take a very long time to render - in my testing, https://elk.zone/mastodon.social/@MarkRuffalo/109638532333776039 took over 10s to fetch from the Mastodon API and then at least as long to render all of the 700+ replies in the DOM.
This PR makes a couple of improvements (including moving to `shallowRef` from `ref` within `useAsyncData`) but the most significant is the switch to using virtual scroller for post replies. It also renders a skeleton when loading the context. In view of past regressions (e.g. on notifications) when adopting virtual scroller, it would be good to have some review and testing before merging.
---
> perf: improve perf on rendering long list of replies

- components/content/ContentMentionGroup.vue
- components/publish/PublishWidget.vue
- composables/masto/account.ts
https://github.com/elk-zone/elk/commit/9571d7338a824865e3ddad7be52587c657b806ea introduced mentions as separate lines. This PR fixes some issues with the new mentions scheme for the PublishWidget:
- wrap mentions (they were getting out of the widget)
- use short handle (like in the messages)
- click to remove (with basic feedback using red color)
Adding a new mention can be done as usual by including it in the message. We can later improve the UI, but I think we could merge this PR to let users delete mentions until we do.
---
> fix: publish widget mentions

- nuxt.config.ts
- tests/__snapshots__/content-rich.test.ts.snap
- tests/__snapshots__/html-parse.test.ts.snap
- tests/content-rich.test.ts
- tests/html-parse.test.ts
- tests/permalinks.test.ts
Use webtoo.ls instead of mas.to as default server, as the content shown by default in the local timeline, is more related to Elk (since its account and the accounts of many of the team members are on it).
---
> chore: webtoo.ls as default server

- components/status/StatusTranslation.vue
- styles/vars.css
This is a style fix for #1211 
Loading text color cannot accessible in light theme.
Before:
After
---
> fix(ui): translation button loading style issue in light theme

- components/status/StatusTranslation.vue
This PR makes the translate button's text size & spacing smaller to make it less stand out and less distracting visually.
| before | after |
| -------|-----|
| <img width="300" src="https://media.discordapp.net/attachments/1045711701359743098/1064674548139687987/image.png"> |  <img width="300" alt="image" src="https://user-images.githubusercontent.com/1430856/212826338-649eb49f-f6d7-44e9-b8bb-b290c842bd1f.png"> |
As I pointed out on [Discord](https://discord.com/channels/1044887051155292200/1045711701359743098/1064674548345225387), the current translate button is a bit too large and visually distracting. Keep it the same size as mention groups, which is `text-sm`, would be more ideal.
---
> fix: make translate button visually less distracting

- components/status/StatusContent.vue
- components/status/StatusPreviewCard.vue
- components/status/StatusPreviewCardNormal.vue
- components/status/StatusPreviewStackBlitz.vue
StackBlitz added the code in the meta description when sharing a URL with `L1-L3` (highlight code in a playground)
https://stackblitz.com/edit/node?file=index.js%3AL1-L3
This would allow us to render the code using shiki instead of using a social image and have a snippet where you can click to see it working in a playground.
The design is still in progress, sending the PR to test and start playing
---
> feat: StackBlitz code block expansion

- config/pwa.ts
- service-worker/sw.ts
We're preparing language country variants and then web manifest number will increase, this PR excludes these files from being precached in the service worker: added route entry in the service worker using network first strategy to allow work offline.
Once `nuxt-i18n` module adds the ability to reuse base locale, we'll start adding country variants: for example, just for spanish country variants there will be 19 new files (19 new web manifests + 19 dark web manifest variants).
> perf: exclude pwa web manifests from sw precache

- server/shared.ts
Because of how we query KV store in unstorage, being able to pass a prefix is important, and this means we can query by host server rather than origin.
It will also reset our oauth data, so 🤷 
---
> perf: use server namespace to simplify kv querying

- composables/content-parse.ts
This PR fixes a backtick escaping.
Example: https://main.elk.zone/m.webtoo.ls/@elkdev@universeodon.com/109703907364081699
---
> fix: use global regex to escape backticks

- components/main/MainContent.vue
Adds `data-tauri-drag-region` to the title bar, which is needed to perform window dragging in the native application.
This change is needed to resolve https://github.com/elk-zone/elk-native/issues/10
---
> fix(native): Enable window draging by the title bar

- components/search/SearchWidget.vue
Search field had `select-none` attribute that blocked keyboard input
Fixes #1272
---
> fix(native): Fixed bug causing inability to enter text in search field

- components/status/StatusActionsMore.vue
- components/status/StatusBody.vue
- components/status/StatusTranslation.vue
- composables/masto/translate.ts
related #1118 #1247(maybe?)
By default, translate post target language will be `navigator.language`, not apply for current selected langauge.
Now will be same as current selected language.
---
> fix: translate posts target language is not current selected language

- components/modal/ModalMediaPreview.vue
Move the alt text under the media preview, instead of in the top-right corner. This make the alt text vertically aligned with the image.
[Before](https://elk.zone/mstdn.social/@elk@webtoo.ls/109642445862735271):
After:
> feat(ui): move alt text under the media preview

- components/search/SearchWidget.vue
Select the first search result when <kbd>Enter</kbd> is pressed, instead of closing the search results.
This is especially useful on mobile devices, since browsers (at least Firefox on Android) only emit text events when a non-letter key is pressed. Actually, using the <kbd>Enter</kbd> key will close the search results instead of performing the search.
---
> feat(search): select first result on enter press

- components/status/StatusBody.vue
- components/status/StatusCard.vue
- components/status/StatusContent.vue
- components/status/StatusDetails.vue
- composables/content-parse.ts
- pages/[[server]]/@[account]/[status].vue
- tests/__snapshots__/html-parse.test.ts.snap
- tests/content-rich.test.ts
- tests/html-parse.test.ts
Hides redundant mentions in status when these are already in context (in the replying to badge or connected to the previous status)
> feat: hide redudant mentions

- composables/content-parse.ts
- tests/__snapshots__/html-parse.test.ts.snap
- tests/content-rich.test.ts
After https://github.com/elk-zone/elk/pull/1293 (and https://github.com/elk-zone/elk/commit/5785047856e10861a1e10d614b18c1cb79591002), if you add a new mention in a conversation, a `mention-group` will be created only with it as the others are removed from the context. This could break the context, especially now that we edit with the grouped mentions so people may start using the initial handle as part of the text. But the main issue to me is that a `mention-group` that only has one or two handles ends up occupying more space extracted than inlined.
This PR lets mentions be inlined when only 1 or 2 remain to be shown and creates a `mention-group` when there are 3 or more.
Elk 0.5.0
Elk before this PR
After this PR
> feat: inline some mentions to reduce spacing

- components/status/StatusActionsMore.vue
- locales/en-GB.json
- locales/en-US.json
This PR adds a new context menu item 'Copy original link to post'. Selecting this menu will copy the original URL to the clipboard, aka without the elk.zone prefix
Fixes #1064
See #1064
> feat: add 'copy original link to this post' menu item

- components/nav/NavLogo.vue
- components/nav/NavTitle.vue
See @antfu's comment here https://github.com/elk-zone/elk/pull/1316#issuecomment-1397079724, it is now a bit confusing to know in what env we are.
This PR tests the idea of using normal color for the nav logo (same as many other apps, like GitHub, Twitter, etc). The brand isn't content for the user, and a big primary color blob in the corner is a bit distracting in my opinion.
The PR also switches to directly change `Elk` by `Dev` or `Main` instead of the superinduce so the layout doesn't change much.
Dev:
> feat: normal text color for nav logo

- components/status/StatusAttachment.vue
- composables/settings/definition.ts
- locales/de-DE.json
- locales/en-US.json
- pages/settings/preferences/index.vue
Added an autoplay setting and functionality to prevent autoplaying videos when the setting is disabled.
The default value is set like the current behaviour, so autoplaying is enabled.
closes #1235
> feat: added autoplay setting

- components/nav/NavSideItem.vue
- composables/screen.ts
This PR aims to keep tooltip vs shown text functionality on SideNavItem consistent. If the text is hidden, show the tooltip (and vice versa).
- Fix #1320 and disable side nav item tooltips on mobile (see the issue for video of the bug in action)
- Enable the tooltip when on a `lg` screen, matching the show/hide functionality on the item's text content
---
> fix: disable side nav item tooltip on small screen

- components/status/StatusTranslation.vue
- composables/settings/definition.ts
- locales/de-DE.json
- locales/en-US.json
- pages/settings/preferences/index.vue
Simply adds the preference to hide the translation button as requested from some users :)
closes #1342
> feat: add user preference to hide translation button

- components/publish/PublishAttachment.vue
The black background makes it a lot more obvious, and let's always leave it there rather than requiring a mouseover. Added the translated text as an aria-label for screenreaders/a11y, because "X" isn't super descriptive.
This takes a chainsaw to the existing image deletion button in the PublishAttachement component, but.. It's currently really hard to find/see, as described in #1067 and #1283.  It also makes it stylishly consistent w/ the Edit button.
This fixes #1067. Tested on both my laptop (firefox 102) and my phone (android 11).
---
> fix: make attachement removal button static & more visible #1067

- components/main/MainContent.vue
- layouts/default.vue
- nuxt.config.ts
- styles/global.css
- styles/scrollbars.css
- unocss.config.ts
- Two new variants have been added to UnoCSS: `native:` and `native-mac:`. Styles for these variants will only be generated if the `TAURI_PLATFORM` variable is properly set during the build process.
- The application now respects the user's system preferences for the style and behavior of the style bar on the Mac
- The title bar is always visible in the app, which should fix a problem when the window was not draggable on larger screens. elk-zone/elk-native#43
- This is not the final iteration, in the future, I plan to move the navigation in narrow windows to the left side.
Here are before and after screenshots:
--
650px:
1000px:
1200px:
1400px:
closes elk-zone/elk-native#44
> feat(native): Improved layout in elk-native

- components/modal/ModalMediaPreview.vue
The close button is moved from left to right of the page.
I worked on this good-first-issue and any feedback is appreciated.
Thanks! :)
> fix: #1348 Improved the close button UI

- components/common/dropdown/DropdownItem.vue
- components/user/UserSwitcher.vue
> fix: add an existing account and Sign out should be `<button>`

- styles/global.css
> fix: rendering of high emoji

- components/tag/TagCard.vue
When navigating over the hashtags links to the hashtags details page, the instance was not included in the URL
this results in that the follow/unfollow button was not displayed
> fix: tag link

- components/settings/SettingsItem.vue
- pages/settings.vue
> fix: settings navigation

- components/notification/NotificationPaginator.vue
See https://elk.zone/fediverse.zachleat.com/@zachleat/109739539249687601 for context.
We got feedback that using a hard limit using the followers count was a bit awkward. We had already discussed something along these lines before and proposed using percentages relative to the user followers count. I think this wouldn't be ok either.
This PR changes the grouping algorithm to test in it in the wild in the next release.
It now orders the group according to who has a header first (giving priority to folks that did setup their account), and who has more followers second. Then it shows the first one of the group (if it has a header) as a big card, no matter how many followers it has. If only one remains and it has a header, it is also expanded as a big card. If not, the remaining are shown as …
> feat: improve follows you grouping

- components/status/StatusPreviewGitHub.vue
Currently(v0.6.1), the avatar will scale with the content on the left.
This PR sets the avatar size to a fixed value of `7.5rem`, and `4.5rem` for small sizes.
---
Image taken from https://elk.zone/@mas.to/@nuxt@webtoo.ls/109738793310974724
> feat: improve github status preview ui

- locales/zh-TW.json
Updated for more commonly used words in Taiwan
---
- Replaced "關注" with "追蹤"
- Replaced "關注者" with "粉絲"
- Replaced "黑名單" with "封鎖"
- Replaced "帳戶" with "帳號"
- Replaced "代碼倉庫" with "儲存庫"
> fix(i18n): Update zh-TW translations

- components/tag/TagActionButton.vue
fixed if condition for following tag
this bug was introduced by https://github.com/elk-zone/elk/pull/1391
> fix: tag if condition

- components/user/UserSwitcher.vue
> fix: make the user switcher's buttons fill container

- service-worker/share-target.ts
Use [303 response code redirection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303): https://developer.chrome.com/articles/web-share-target/#processing-post-shares suggest using 303
> fix(pwa): use 303 redirect in web share target api

- composables/masto/statusDrafts.ts
> fix: default user language when writing a publication

- CONTRIBUTING.md
- locales/en-US.json
- package.json
- pnpm-lock.yaml
This is the final update for country variants: 
- nuxt i18n module fix merging files and `en-US` is now correct
- update contributing guide to remove the workaround
> chore(i18n): update i18n module and `en-US` file

- nuxt.config.ts
Noticed cannot zoom on mobile devices at all because it's completely disabled on meta viewport. I don't understand the reasoning behind this. I know there is a font-size scale setting but it's not sufficient for many users with the problems on eye-sight. As Elk works as PWA, zooming should always be enabled.
The `maximum-scale` parameter limits the amount the user can zoom. This is problematic for people with low vision who rely on screen magnifiers to properly see the contents of a web page.
Users with partial vision and low vision often choose to enlarge the fonts or other elements on their browser to make text and images on the web easier to read and recognize. The browser's viewport focus is everything visible in the browser window at a given moment. Maximizing the browser to full …
> fix(a11y): do not prevent arbitrary zooming on mobile devices

- pages/[[server]]/public/index.vue
Fix the wrong icon used in Federated Timeline title bar. It should be the same `earth` icon as in side bar, not the `group` icon used by Local Timeline.
> fix: correct federated timeline title icon

- components/status/StatusActionButton.vue
Disable selection on `StatusActionButton`. Selection is easily trigger on iOS when doing long press on action buttons like boost.
#1132 #1147 #1219 
---
> fix: disable user-select on StatusActionButton component

- components/command/CommandPanel.vue
This replaces the wrong "Ctrl" with "Command" as a modifier key name in the command pallet on macOS.
**Before**
**After**
I used `navigator.userAgentData.platform` to detect the platform name. However, this is implemented only in Chromium-based browsers at this moment.
ref. ["userAgentData" | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/?search=userAgentData)
If we want to work this on any browser, we need to use another way until all major browsers implement `userAgentData`. Then, does anyone know the best way to reliably detect the macOS in the Vue ecosystem?
> fix: use "⌘" as modifier key name on macOS

- modules/tauri/index.ts
- modules/tauri/runtime/storage-config.ts
- nuxt.config.ts
- server/shared.ts
follow-up on https://github.com/elk-zone/elk/pull/1508
This makes the choice of unstorage driver fixed at build-time, to avoid including more dependencies than needed. I think it's unlikely users will swap between cloudflare/memory/fs at runtime.
> perf!: allow tree-shaking unstorage drivers

- styles/global.css
This PR is related to https://github.com/elk-zone/elk/pull/1501
/cc @ronilaukkarinen can you test pinch to zoom in this PR preview? Your fix not working on my Android device, there is some pan x/y in body styles that prevents it.
https://streamable.com/y6cnyy
> fix(a11y): allow pinch to zoom

- components/common/dropdown/DropdownItem.vue
The hover style of the account setting button is strange. Give it a 'width: 100%' maybe look better.
> fix: account setting button hover style

- styles/global.css
A visual representation of the issue:
After this change:
To think about in the future: There's an incosistency here, because in the post the emoji is wrapped with a class custom-emoji whereas in the editor the custom-emoji class is directly in the img.
> fix: Custom-emoji size on editor

- nuxt.config.ts
#1501 remove `viewport-fit=cover` caused this problem in iOS PWA
> fix: viewport meta value for iOS PWA safe area

- components/status/StatusPreviewCard.vue
- components/status/StatusPreviewStackBlitz.vue
This PR updates StackBlitz card to a new description format. It also fixes output of html code.
Before: https://elk.zone/universeodon.com/@elkdev/109790480026907676
After: https://deploy-preview-1562--elk-zone.netlify.app/universeodon.com/@elkdev/109790480026907676
> fix: update stackblitz card to a new format

- components/status/StatusPreviewGitHub.vue
- package.json
- pnpm-lock.yaml
This PR fixes some problems with GitHub preview card:
- it fixes a problem with parsing of repos with `.` in name
- it also adds a fallback for (hopefully) all reserved paths from the `github-reserved-names` package. It also adds a whitelist for all supported reserved paths (only `/sponsors/{username}` at the moment)
Thread with some broken links:
https://elk.zone/universeodon.com/@elkdev/109790632883374579
> fix: update GitHub card paths lookup

- plugins/setup-i18n.client.ts
This PR fixes missed language code fallback.
How to test:
- go to local storage and update language code to smth like `foo-FOO`
- reload the page
- it would error out before the fix
> fix: missed language code fallback

- components/list/ListEntry.vue
- components/nav/NavSide.vue
- locales/en.json
- locales/es.json
- pages/[[server]]/list/[list]/index.vue
- pages/[[server]]/lists.vue
This PR includes 
- `user-only` on navigation 
- `auth` middleware in lists and list pages
- spanish translation for new entries
> fix: list should be user-only

- components/nav/NavSide.vue
The list side nav item is pointing to the wrong link, also, you could have redirection to home when opening in a new tab:
**ACTUAL**
**FIXED**
> fix: lists link on side nav

- composables/push-notifications/usePushManager.ts
> fix: undo changes on push notifications settings stops working

- layouts/default.vue
Attribute `zen-hide` is not working (cc @antfu any idea?)
Resolves #1605
> fix: hide side nav in zen mode

- components/account/AccountHeader.vue
- components/status/StatusAttachment.vue
- composables/settings/definition.ts
- locales/en.json
- pages/settings/preferences/index.vue
consider merging without squashing, each fix is contained in it's own commit
- feat: add outline to verified links closes #155
- fix: remove saturation for links fixes #1528
- feat: option to hide alt indicator closes #1410
- add wellness section to preferences (no issue?)
> feat: quickfixes

- components/modal/ModalMediaPreviewCarousel.vue
fix #1595
We should discuss the UX of this code before I mark it as ready for review, I'd reckon.
> feat: image pinch to zoom

- components/notification/NotificationPreferences.client.vue
- components/notification/NotificationSubscribePushNotificationError.vue
- composables/push-notifications/createPushSubscription.ts
- composables/push-notifications/types.ts
- locales/en.json
- locales/es.json
> feat(pwa): add more errors and elk repo link in push notifications subscription errors

- composables/masto/statusDrafts.ts
closes #1609 
This PR sets the default language on replys to the language of the original status
> fix: reply language defaults to status language

- components/conversation/ConversationPaginator.vue
- components/status/StatusContent.vue
- composables/timeline.ts
- tests/unit/reorder-timeline.test.ts
fixes #1027 
- Do not filter your own authored posts
- Spoiler text should be prioritized if filter phrase also exists
for test post 👉 https://elk.zone/social.ayco.io/@ayo/109677886156981992
| main.elk.zone | preview with fix | mastodon web |
| --- | --- | --- |
| <img width="603" alt="Screenshot 2023-02-05 at 12 11 31 PM" src="https://user-images.githubusercontent.com/4262489/216815486-c9b20fad-5231-4f29-89f3-64cc15efbebd.png"> | <img width="620" alt="Screenshot 2023-02-05 at 12 11 44 PM" src="https://user-images.githubusercontent.com/4262489/216815492-d926534e-ffe5-4cf6-ae18-64ee8d355cf1.png"> | <img width="594" alt="Screenshot 2023-02-05 at 12 11 51 PM" src="https://user-images.githubusercontent.com/4262489/216815497-6a1a3d94-7817-4436-bf84-3670b5c3d609.png"> |
> fix: filter and cw logic

- components/status/StatusCard.vue
(This is a re-opened PR of the previous PR #1619 in which I forgot to rename my branch.)
Resolve #1541
When a user reblog a post without comment, some non-mastodon servers like Akkoma and GoToSocial copy the content of the original status to the content of the new reblogging status, instead of leaving it empty.
Currently, Elk treats this as **reblogging with comment**, and displays both `status.content` and `status.reblog.content`. As a result, the content is displayed twice.
After this fix, `StatusCard.vue` will consider both **reblog with empty `status.content`** and **reblog with repeated `status.content`** as **reblog without comment**, and display it with corresponding format.
> fix: repeated content on reblog without comment (re-open)

- components/publish/PublishLanguagePicker.vue
closes #1548 
if the user has configured one or more language not to translate (aka known languages), these languages get prioritized in the language picker because these are most likely the languages the user is searching for.
> feat: prioritize user languages in language picker

- components/publish/PublishWidget.vue
- composables/masto/publish.ts
- composables/masto/statusDrafts.ts
resolves: #1512
In Mastodon, content warning (spoiler text) will be included in the character count
But not currently
After this PR, when the content warning (spoiler text) is activated, it will be included in the word count, and it will be ignored when it is closed.
https://user-images.githubusercontent.com/39984251/215755701-69f024c9-969f-403f-8fc6-90f535b40079.mp4
> fix: character count should includes spoiler text

- components/common/CommonInputImage.vue
- components/modal/ModalMediaPreviewCarousel.vue
- components/tiptap/TiptapEmojiList.vue
- composables/masto/publish.ts
- composables/tiptap.ts
- composables/tiptap/suggestion.ts
- composables/users.ts
- mocks/class.ts
- mocks/eventemitter.ts
- mocks/prosemirror.ts
- mocks/tiptap.ts
- nuxt.config.ts
- pages/settings/users/index.vue
This takes the node server build output (including dependencies) from 23M -> 9.8M.
It also improves compatibility with cloudflare target, though I'm not sure we're fully there.
> perf: tree-shake dependencies from server

- server/cloudflare-driver.ts
- server/shared.ts
https://github.com/unjs/unstorage/pull/138
A bug in upstream unstorage driver meant params were never passed to fetch request, so when we were calling `/api/list-servers` we were fetching the same first request, over and over, until a server timeout.
This hotfixes it within elk until upstream fix lands.
> fix: work around hotfix cloudflare kv storage bug

- components/publish/PublishWidget.vue
Fix #1651 
limit length of links counting towards character limit to 23
Signed-off-by: Chris-Robin Ennen <chris-robin@ennen.dev>
> fix: only count 23 characters per link when composing

- components/status/StatusReplyingTo.vue
"Replying to" was breaking on small screens / mobile devices.
Before:
After:
> fix(ui): Prevent word-wrap on "Replying To"

- components/status/StatusAttachment.vue
- styles/global.css
- unocss.config.ts
Hi!
This prevents videos from clipping (display-mode: cover) when in fullscreen.
~~I'm looking for better unocss ways to accomplish this, but I havenoideawhatI'mdoing.jpg so any advice would be appreciated. :) Thank you!~~ Now resolved, thanks @kreha1!
Edit: Worth noting this doesn't affect iOS - it's only a problem on desktop (tested on macOS, should also affect Windows) with chrome/ff/safari.
This is mainly a problem when you try to fullscreen a portrait video on a landscape (aka, regular laptop) screen.
> fix: prevent videos from clipping when in fullscreen mode

- nuxt.config.ts
- package.json
- pnpm-lock.yaml
- server/cache-driver.ts
- server/utils/shared.ts
We have an issue with an undefined variable being thrown by vue-router. This reverts the upgrade to nuxt v3.2.0 until we have a chance to investigate further.
Reverts elk-zone/elk#1684
resolves https://github.com/elk-zone/elk/issues/1690
> fix: revert upgrade to nuxt v3.2.0

- components/publish/PublishWidget.vue
- composables/masto/statusDrafts.ts
This PR changes default privacy setting of a post by considering the account's preferenced privacy setting when starting composing a post.
Also fixed an existing issue that empty drafts were not always cleared.
Fixes #1040 #1199
> feat(editor): Respect default privacy setting of the account

- composables/setups.ts
The list of locales from the `i18n` module contains explicit `dir` property for RTL languages. The rest of the LTR languages have `dir` `undefined`.
I believe it's sufficient to default the `html` tag `dir` to LTR, as the majority of the content on the page should be user language specific and not derived from the currently present post language _(and language direction)_.
`dir="auto"` infers the language direction from parsing the characters inside the element _(`html` in this case)_, until it finds **a character with a strong directionality**, according to [MDN `dir` docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir)
Fixes: #1569
> fix: default main content dir to ltr

- components/user/UserSignInEntry.vue
- locales/en.json
- locales/es.json
The message in `UserSignInEntry` includes `, or interact from your account on a different server.`, on single instance server there is only 1 server, the default.
> fix(i18n): better login description for single instance server

- locales/pt-PT.json
Add and translate 2 new keys:
- profile_metadata_label
- profile_metadata_value
> fix(i18n): update portuguese from Portugal translation

- scripts/prepare-translation-status.ts
Running `postinstall` script fails (json on ESM).
> fix: prepare translations status on codeflow fails

- composables/setups.ts
Just see on opening Elk, we can see empty vertical bar:
> fix: remove alone vertical bar on start

- plugins/social.server.ts
Add the WhatsApp user-agent to the bot regex.
I don't use WhatsApp myself, but I tested this with Signal, which sends a `WhatsApp/2' user-agent for link previews.
> fix: return redirect for whatsapp user agent

- CONTRIBUTING.md
- docs/components/global/TranslationState.vue
This PR also updates nuxt-i18n link: old one pointing to Nuxt 2 docs
> docs(i18n): include translation status in contributing guide

- components/modal/ModalMediaPreviewCarousel.vue
I saw this zoom bug and it's also mentioned here: https://github.com/elk-zone/elk/pull/1620#issuecomment-1427096398
**Before**:
- On desktop, use pinch gesture on touchpad
- Zoom out of the image → Image scaled down
- Further pinching makes the `scale` to go negative thus flipping the image up-side-down
https://user-images.githubusercontent.com/2296/218365340-0683509c-b7c2-4fff-b663-2630aee4beca.mp4
**After**:
- Prevent the `scale` from becoming negative.
- I figured that might as well make the limit 0.5 instead of zero? I can't think of a reason for anyone to zoom out so much 😅
https://user-images.githubusercontent.com/2296/218365656-694c89a0-e6da-4208-93ce-9b9d2f02d87c.mp4
Tested on Chrome v109.0.5414.119 (Official Build) (arm64) and Edge v109.0.1518.78 (Official build) (arm64) on MacOS …
> fix: limit pinch scale to minimum 0.5

- components/status/StatusReplyingTo.vue
- Fix #1663 that breaks the word order of translation
- To keep it one-line, make it a flexbox and wrap `<AccountInlinInfo>` with a little margin to compensate loss of word spacing; don't know if it's a good idea but looks best among what I tried
https://github.com/elk-zone/elk/blob/635d55befbb71e0f36a91b63d251099d6015c3bb/locales/tr-TR.json#L375
Before | After
:-: | :-:
> fix(ui): unintentionally hardcoded word order of status.replying_to

- docs/content/80.pwa.md
@userquin  I created a new section on the PWA status of browsers on iOS other than Safari and added one more step (on port forwarding) in the 'Debugging PWA in mobile browsers' section, becuase I think it was missing.
> docs: docs/pwa improvements

- components/notification/NotificationPreferences.client.vue
- components/notification/NotificationSubscribePushNotificationError.vue
- docs/content/80.pwa.md
- locales/en.json
- locales/es.json
This PR adds always a new hint on push subscription error, the new hint will link to PWA FAQ in docs.
When merged, we should also deploy docs.
> feat(pwa): add FAQ to PWA docs and link on push subscription error

- locales/es.json
The current translation implies a request to follow you has been made (instead of requesting to follow someone). The phrase was also not stated as a verb, as the other actions.
> fix: Spanish translation for request to follow is incorrect

- package.json
- pnpm-lock.yaml
Resolve #1473.
The upstream project [masto.js](https://github.com/neet/masto.js) resolved the issue neet/masto.js#833 by the PR neet/masto.js#857, and included that PR in the latest release 5.9.2.
This release helps resolving #1473. All we need to do is just upgrading the package `masto` to version 5.9.2 or newer.
> fix: update masto.js to 5.9.2

- .vscode/settings.json
As we have now variants enable, en-US is no more the source of language as it's a variant itself.
So, I suggest to switch too EN ~~and force the [BCP47](https://en.wikipedia.org/wiki/IETF_language_tag) language system~~
> chore(i18n): `en` as source language

- scripts/prepare-translation-status.ts
Changes on vscode settings file breaking installing deps: prepare translation status script failing
> fix: installing deps on main error

- CONTRIBUTING.md
Fixed some typos while testing something in pr.new
> docs: fix typos in readme

- composables/content-parse.ts
It would appear that the current markdown replacer function for bolded italics (line 448) that converts a match into an ultrahtml `h()` object doesn't expect an array in `c`'s place.
https://github.com/elk-zone/elk/blob/29b37e67c7675d65a554aac05f742922771484bf/composables/content-parse.ts#L447-L455
When supplied with c = `['foo']`, it simply puts `['foo']` in the elements children, which isn't properly parsed by Vue. If instead, it is in the form `'foo'`, it's parsed properly.
I'm not too familiar with ultrahtml but this seems to work for me and seems to be the root cause as far as I can tell.
Before: (Screenshot taken from mocked dev, but I'd guess viewing [this](https://universeodon.com/@yenche123/109895545528086301) would yield similar results)
After:
Fixes #1804.
> fix: properly parse bolded italics

- Dockerfile
UID and GID arguments where swapped
> fix: unswap uid/gid in dockerfile

- components/status/StatusPoll.vue
Percentages currently use `votesCount`, regardless of whether the poll is a regular poll or a multiple choice one. It should instead read the computed `votersCount`, which is already used to display the (correct) percentages.
Example poll ([link](https://mastodon.social/@emilydoesastro@mstdn.social/109880570959162892)):
Before ([elk link](https://elk.zone/mastodon.social/@emilydoesastro@mstdn.social/109880570959162892)):
After ([deploy preview link](https://deploy-preview-1821--elk-zone.netlify.app/universeodon.com/@emilydoesastro@mstdn.social/109880570340375814)):
Fixes #1780.
> fix: display correct percentages for multiple choice polls

- styles/global.css
Referencing issue: #1551 
Referencing PR: #1503 
Thought I already fixed this, was kinda waiting it to be effective. Not thoroughly tested by me it seems, for this I apologize. There is an inconsistency, since everywhere else it's `.custom-emoji img` where as inside editor it is `img.custom-emoji`.
This time I tested it thoroughly and confirmed working:
> fix: Custom-emoji size on editor revisited

- locales/en-GB.json
- locales/en.json
For consistency with the other occurrences of _favo(u)rite_
> fix(i18n): use American spelling

- components/status/StatusPoll.vue
If `votersCount` is 0, then we possibly have a 0/0 resulting in a NaN `--bar-width`, which is displayed as a 100%.
This PR fixes this. Also, I added a minimum width of 1% which isn't quite related to this issue but Mastodon does it. If that's not preferred, then let me know and I'll remove it.
Original ([mastodon](https://mastodon.social/@probatio/109930593995266040)):
Elk canary ([link](https://main.elk.zone/universeodon.com/@probatio@mastodon.social/109930593983351304)):
Patched ([link](https://deploy-preview-1826--elk-zone.netlify.app/universeodon.com/@probatio@mastodon.social/109930593983351304)):
> fix: avoid bar width division by zero

- composables/masto/publish.ts
- nuxt.config.ts
Mastodon's API has a [4096x4096px file size](https://github.com/mastodon/mastodon/blob/730bb3e211a84a2f30e3e2bbeae3f77149824a68/app/models/concerns/attachmentable.rb#L8) limit on image attachments, its web client however simply resizes larger images on the client-side to an acceptable size for the API request.
This PR brings this functionality to elk. The approach is [based on theirs](https://github.com/mastodon/mastodon/blob/730bb3e211a84a2f30e3e2bbeae3f77149824a68/app/javascript/mastodon/utils/resize_image.js), though re-written by myself in a much more stripped down way.
To test, try uploading a large attachment [like this one](https://unsplash.com/photos/7f4WaNrR4uo/download?force=true).
Fixes #1702
> fix: resize large images attachments on upload

- composables/masto/statusDrafts.ts
Automatically inserts content warnings when applicable.
> feat: copy content warning when replying

- composables/content-parse.ts
- composables/content-render.ts
Currently, if we have a `<pre>` with a nested `<code>`, we assume that there's only one child within that code block. But in some cases, we might find some `<br>`s in there causing there to be more than just one child. So we don't want to only consume the first child and throw the rest away, rather we want to properly consume each child.
This could be done iteratively or recursively. I chose to go with the recursive solution since since we might possibly run into a few odd situations in which code blocks (for whatever reason) might have children that then have other nested children (not something to normally expect, but then again, who expects `<br>`s in `<code>`s like what happened just now?).
Before screenshot ([canary link](https://main.elk.zone/social.treehouse.systems/@alyssa/10993342 …
> fix: allow parsing codeblocks with multiple text nodes in children

- components/publish/PublishWidget.vue
As mentioned from the [docs link](https://docs.joinmastodon.org/user/posting/#mentions) in the [referenced issue](https://github.com/elk-zone/elk/issues/1803)
> You can mention users by typing out their full address, e.g. @[alice@example.com](mailto:alice@example.com). Note that any usage of@word will be interpreted as mentioning the local user with the username word, if that user exists. Only the username part will count against your character limit – the domain is not counted.
I've taken a look at how mastodon themselves deal with this and used their regex (with attribution in a comment) since I assume theirs would handle any weird edge cases.
Mastodon:
Elk canary (incorrect, 6 characters expected):
This patch:
This should be fine. I tested it with a bunch of random text and it matches …
> fix: only use username part of mention

- docs/content/1.guide/2.features.md
Adds initial set of content to the features page of the docs.
Discusses 
- Multiple accounts
- Rich text
- Code blocks
- Connected linked posts
- Improved notifications
> docs: Add content for feature page

- composables/masto/icons.ts
- package.json
- pnpm-lock.yaml
Add metadata icon for [Matrix](https://matrix.org/).
I don't know what's the "popularity threshold" to add a metadata icon, but I already noticed a bunch of accounts (including myself!) adding their Matrix username to their profile.
Matrix is a decentralized, e2e encrypted, chat protocol. It's used by a variety of organizations, such as TC39, WHATWG, Mozilla or Germany's national healthcare system.
Mastodon : Twitter = Matrix : Discord 🙂
> feat: add metadata icon for Matrix

- components/publish/PublishAttachment.vue
- components/publish/PublishCharacterCounter.vue
- components/publish/PublishWidget.vue
Mastodon enforces a 1500 character limit on media attachment descriptions. This is visible in their interface too:
Elk on the other hand has no such indicator:
As such, it enforces no limits on the attachment length, and so if you post something exceeding 1500 characters, you get this in your console:
This error is not visible to the user (due to it not being captured in `failedMessages` since the error occurs in `setDescription` (`publish.ts`) which has no access to that array)
In any case, the potential solutions to this issue would be as follows:
- Let the user enter a large description, but display the error once they apply the description
- Indicate to the user how many characters have been entered and how many are left, and prevent setting descriptions that exceed that value
I chose …
> fix: disallow media description exceeding limits

- components/status/StatusContent.vue
This fixes a regression introduced in #1633 that causes spoilers to be disabled if media is non-sensitive, when the expected behavior would be to: "enable spoilers as long as there's **[spoiler text or sensitive media]** or [if its filtered]".
I'm fairly sure that this should be as simple of a fix as that, but I think @ayoayco would be able to verify if anything else needs to be addressed.
(again, not evident in these screenshots but this post has `sensitive: false`)
Original instance ([link](https://infosec.exchange/@catsalad/109890930166069976)):
Elk ([canary link](https://main.elk.zone/infosec.exchange/@catsalad/109890930166069976)):
With this fix ([preview link](https://deploy-preview-1864--elk-zone.netlify.app/infosec.exchange/@catsalad/109890930166069976)):
Fixes #1846.
> fix: wrap non-sensitive spoilers in spoiler status

- components/nav/NavBottom.vue
_Partially_ addresses #1422.
Only thing left would be making the last item (more menu) focusable (and presumably toggle-able using Space/Enter?). I'm not too experienced with a11y but I've observed the following when making changes to the `<label>` in the more menu:
* adding `role="button"` allows using Space/Enter to toggle on Firefox 110.0. But does not make it focusable
* adding `tabindex="0"` makes it focusable / tab accessible but hitting Space/Enter no longer triggers a toggle
Maybe someone could suggest/co-author the proper fix for the more menu so that the linked issue could be closed, or we could just merge this now and address that later.
> fix(a11y): add aria labels to bottom navigation links

- composables/content-parse.ts
Reference:
- #1871
@cyberalien it looks like when we copy and paste, there is no `title` in the attributes and we are instead adding a `alt` that has the full `:name:`
This PR fixes copy and paste, but I don't know if this is correct long term. We also are creating [here](https://github.com/elk-zone/elk/blob/fa3cfd6059f2bdd42bc5d349ac225c29c6f666de/composables/content-parse.ts#L429) a custom emoji without a title but this one has a `emoji-data-id`
Looks like the `emoji-data-id` is lost on copy and paste.
We could still merge this one as a patch.
> fix: copy and paste custom-emoji

- docs/app.config.ts
It was bothering me that the docs had a link to twitter and not mastodon, while Docus doesn't have native mastodon support it does allow for arbitrary social networks.
> docs: add mastodon link to header

- README.md
Remove Freelancers.online from ecosystem. 
Project and server no longer going forward.
> chore: update ecosytem link

- components/notification/NotificationCard.vue
- components/notification/NotificationGroupedLikes.vue
- components/notification/NotificationPaginator.vue
- components/status/StatusCard.vue
- components/status/StatusContent.vue
- components/status/StatusLink.vue
Before/After
Made based on a few assumptions:
- People don't usually need to directly interact with the post in notification
- The post author already has the context of the post; Having media and polls are usually redundant
- Notifications should be concise and fix as much info as possible on one screen.
- We don't need to duplicate our avatar and name in the notification
cc @patak-dev let me know WDYT :)
> feat: simplify notifications

- docs/content/80.pwa.md
PR #1758  moves PWA plugin to add pwa plugin stub when PWA disabled, now it is located on pwa module runtime folder
> docs(fix): pwa plugin link

- public/robots.txt
Fixes invalid syntax in `robots.txt` file (missing colons)
> fix: syntax for robots.txt disallow rules

- modules/pwa/index.ts
Nuxt DevTools shows we're using `nuxt/pwa` module instead custom one.
With this change:
> chore: change pwa module name

- modules/pwa/i18n.ts
This adds the `any` purpose to our normal PWA icon and reserves `maskable` for just the maskable icon. It looks like this should improve rendering of the PWA icon.
See https://docs.pwabuilder.com/#/builder/manifest?id=icons.
> fix: use `purpose: any` for normal pwa icon

- locales/es.json
Updated missing keys at `es` base lang: 
`account.profile_personal_note`
`menu.add_personal_note`
`menu.remove_personal_note`
cc @userquin
> feat(i18n): sync `es` base lang

- pages/settings/profile/appearance.vue
We need to add `@server` to the acct account response and override account cache, check:
- https://github.com/elk-zone/elk/blob/main/composables/users.ts#L147
- https://github.com/elk-zone/elk/blob/main/composables/users.ts#L172
closes #1879
> fix: saving profile data breaks cache

- components/account/AccountHoverCard.vue
- components/account/AccountPostsFollowers.vue
- components/common/LocalizedNumber.vue
From @patak-dev 's idea (see [here](https://github.com/elk-zone/elk/pull/1897#pullrequestreview-1344639293)), I adjusted the wellbeing "Hide following/follower count" feature.
Before changes, when "Hide following/follower count" is enabled, the following count and the follower count are hidden as shown below.
After changes, when "Hide following/follower count" is enabled, only the numbers are hidden. The text "Following" and "Followers" are kept so that users are still able to click them to view the following list and the follower list.
> feat: allow user to view follow list in "Hide following/follower count" mode

- composables/content-parse.ts
Fixes #1932
Fixes #1994
@antfu do you recall why we wanted to preserve unicode emojis here? It seems that converting them is the right thing to do so TipTap can properly handle them.
> fix: unicode emojis when editing

- components/magickeys/MagickeysKeyboardShortcuts.vue
- components/nav/NavBottomMoreMenu.vue
- components/nav/NavFooter.vue
- components/status/StatusActionsMore.vue
- components/status/StatusCard.vue
- composables/command.ts
- composables/settings/definition.ts
- locales/en.json
- pages/settings/preferences/index.vue
- plugins/magic-keys.client.ts
- plugins/setup-global-effects.client.ts
- plugins/setup-head-script.server.ts
> fix: Add zen mode to preferences, remove shortcut 

- components/main/MainContent.vue
This PR configures the main content container to be sticky on settings pages, this way the mid panel will not scroll: added logic to keep current behavior when the content height is smaller than the available vertical space.
https://streamable.com/fdyl2w
> feat(ui): use sticky position on settings mid panel

- locales/es.json
New entries:
```
settings.preferences.zen_mode
settings.preferences.zen_mode_description
status.account.suspended_message
status.account.suspended_show
```
Removed entries:
```
magic_keys.groups.actions.zen_mode
``` 
/cc @mrcego
> feat(i18n): Update Spanish translations

- styles/global.css
Fixes #1983
@userquin @cyberalien maybe you could check this one? I don't know why we were using different sizes for custom emojis and for normal ones, and why we were using max-width/max-height instead of direct width/height.
The forest repro looks good after this PR
> fix: emoji sizing

- CONTRIBUTING.md
This request change [en-US](./locales/en-US.json) to [en](./locales/en.json) as the default guide to copy for the translation. Since [en-US](./locales/en-US.json) is an empty objects.
> docs: update translation guide file to copy

- components/common/CommonBlurhash.vue
- components/status/StatusAttachment.vue
- components/status/StatusPreviewCardNormal.vue
- nuxt.config.ts
- package.json
- pnpm-lock.yaml
theoretically closes #1954
https://caniuse.com/intersectionobserver
> feat: lazy load images

- composables/misc.ts
Takahē hashtag links always end with a trailing slash which Elk's regex didn't recognize. With this change hashtag URLs are allowed to have an optional trailing slash.
i.e. `https://takahe.social/tags/takahe/`
> fix: detect Takahe hashtags correctly

- layouts/default.vue
- unocss.config.ts
This PR fixes issue #1279 which overflows the user avatar section and footer. The issue is documented [here](https://web.dev/viewport-units/), where 100vh will take 100% of viewport height regardless of UI chrome. This is solved using the `dvh` unit which changes based on the UI.
This issue only affects tablets at >1280px width (eg: 11/13in iPad Pro).
I'm not very knowledgable in unocss syntax, but copied the `scrollbar-hide` implementation since it applies a non-standard CSS rule-set. Reason being is if they are applied directly to tag (eg: `<div h-screen h-100dvh>`, it can not apply correctly if `h-screen` is after `h-100dvh` in the stylesheet.
The CSS rule I created merges the two to read like so:
```
.h-100dvh {
height: 100vh;
height: 100dvh;
}
```
Where it will apply 100dvh where it …
> fix(default): update layout to use dynamic vh

- components/status/StatusActionsMore.vue
- components/status/StatusDetails.vue
- pages/[[server]]/@[account]/[status].vue
fixes #1335 
will re-fetch status after editing success.
> fix: not refresh status after edit

- components/common/CommonPaginator.vue
- components/list/Lists.vue
- components/timeline/TimelineBookmarks.vue
- components/timeline/TimelineFavourites.vue
- components/timeline/TimelinePaginator.vue
- locales/en.json
> feat: better messages for no favourites and bookmarks

- components/nav/NavSide.vue
- components/nav/NavSideItem.vue
A vertical scrollbar can appear in the left sidebar if the screen isn't large enough. We currently have a lot of spacing. After this PR, the spacing will be collapsed if the height of the screen is small.
Note: I did this with CSS as I don't know how to do it with unocss. We could merge and if later someone wants to rework this in a more idiomatic way, we could update it.
> feat: height responsive sidebar

- components/publish/PublishLanguagePicker.vue
This is a really small but effective change!
Issues like https://github.com/elk-zone/elk/issues/967 are asking for improvements for the language selection. I'm also affected by this myself, because my native language is german but I write posts in english very often.
So english is (I assume) the most common language in the world and many folks write post in english beside their native language. That's why now this PR moves `en` to the top if nothing was searched for manually.
I think this is the most easiest and smallest solution for now we could think of. If we want to improve it further with any smart stuff, we could enhance and iterate later in further PRs.
> feat: prefer en language as top

- components/status/StatusContent.vue
- components/status/StatusSpoiler.vue
- composables/users.ts
- locales/en.json
- locales/tl-PH.json
- pnpm-lock.yaml
fixes #1002 
This PR will respect two preferences with regards to media display: `show all`, or `hide all`
1. `show all` will expand all media hidden under a spoiler UI
2. `hide all` will put all media (even non-sensitive ones) under a spoiler UI
Also added a new translation string to mark if media is hidden, same with Mastodon web. Example below is a non-sensitive post but hidden to respect the "hide all" preference:
| Mastodon | Elk |
|--------|--------|
| <img width="572" alt="Screenshot 2023-05-05 at 11 22 44 AM" src="https://user-images.githubusercontent.com/4262489/236422064-0ad5f21b-801f-4ac9-b270-138ce1e13a3b.png"> | <img width="595" alt="Screenshot 2023-05-05 at 11 22 54 AM" src="https://user-images.githubusercontent.com/4262489/236422010-f46c4b94-e417-425c-afea-bf13ace48aa9.png"> …
> feat: respect Media Display preferences

- composables/users.ts
If fetching preferences fail, continue with no known preferences.
Some servers (such as the current latest version of GoToSocial)
has not implemented the `GET /preferences` endpoint. This API call is failing
and causing the whole `fetchAccountInfo` function to throw,
effectively logging the user out.
I've also contacted the GoToSocial guys to quickly write up an endpoint,
but this would be a quicker fix as opposed to all GtS users failing to log into
their instance from Elk (we get logged out immediately after authentication as of now).
Note that some of the preferences shown up in the API,
particularly `reading:expand:media` and `reading:expand:spoilers` doesn't seem
to even have an endpoint where it can be set at the moment.
I don't know what is the standard for "show an error, that is …
> fix: Handle failure when fetching user preferences

- components/status/StatusContent.vue
- locales/tl-PH.json
This PR will fix a regression on my last PR where if a post is sensitive but does not have a media attached, it shows the spoiler UI. Also sneaked in a fix for a typo in the Tagalog translation
> fix: regression with media hidden

- components/nav/NavSide.vue
- layouts/default.vue
It doesn't seems we'll be adding things on the right sidebar for a while more, and moving the search widget to the left was a controversial move from the start.
I'm thinking we should move it back to the right, at least until we have more things in that sidebar to justify the move.
> feat: search back to the right

- components/nav/NavSide.vue
- components/nav/NavTitle.vue
We received feedback that:
- It is confusing to have two Compose buttons + the upper publish widget (after adding the one at the top)
- We add the compose button because it was difficult to spot "compose" after we added it to the sidebar as a route instead of a button.
This PR removes the new compose button at the top and instead makes the "compose" on the sidebar more prominent and different from the rest:
- a new spacer above it
- only one using a fill icon, and the icon is always primary (like the button above)
- text is bold
I think this is a good middle ground to try. I would still prefer to avoid using a big orange Compose button on the sidebar. I think it is too distracting (the reason that pushes us in the route direction)
> feat: review compose buttons

- components/status/StatusContent.vue
It seems some servers sending empty expoiler text.
closes #2090
> fix(ui): handle empty spoiler text

- composables/cache.ts
- composables/users.ts
We were constructing the `acct` for the active user as `handle@server` instead of `handle@domain` (for example `vite@m.webtoo.ls` instead of `vite@webtoo.ls`). You can reproduce by hovering over your account on the user picker, and if you click on it in the URL you'll see a URL like `https://elk.zone/m.webtoo.ls/@elk@m.webtoo.ls` instead of `https://elk.zone/m.webtoo.ls/@elk`.
@userquin, in the end, we had everything in place to respect the instance domain (using `uri` in Mastodon and also supporting GoToSocial). This was also used as the key in local storage so there is backward compat code.
> fix: user acct not respecting domain

- components/common/CommonCheckbox.vue
- components/publish/PublishWidget.vue
- composables/masto/publish.ts
- composables/masto/statusDrafts.ts
- locales/en.json
- types/index.ts
A PR for the much requested poll creation feature! 🥳 
Since this modifies the status creation process, it's probably best to do rigorous testing for bugs.
https://github.com/elk-zone/elk/assets/24935987/253263f3-5d6b-4a78-9fd4-f1dff6ed748f
closes #1769
closes #1668
> feat: poll creation

- .github/workflows/docker.yml
This makes it easier to run the CI on forks. See a working run: https://github.com/Joshix-1/elk/actions/runs/5006172477
> chore: publish docker images on forks

- composables/masto/publish.ts
When the amount of options equalled the maximum, the code would remove the (now non-existent) last empty entry, making it remove an actual option.
I also fixed the n >= 2 check to disregard the last entry if it's empty
> fix: poll would sometimes remove last entry

- modules/pwa/index.ts
- package.json
- pnpm-lock.yaml
`vite-plugin-pwa` custom sw build running Vite build without `publicDir: false` and so pwa icons from public folder overrides Nuxt build.
This PR also includes Vite plugin to serve PWA dev icons when running dev server.
> fix(pwa): pwa icons in dev and build

- docs/README.md
To close #2138, I clarified the alt text in the examples provided and added a link to a guide to writing good alt text.
> docs: add alt text instructions

- components/account/AccountFollowButton.vue
- components/account/AccountMoreButton.vue
- components/modal/ModalContainer.vue
- components/report/ReportModal.vue
- components/status/StatusActionsMore.vue
- composables/dialog.ts
- composables/masto/relationship.ts
- locales/en.json
Adds a modal dialog flow for reporting posts. Mostly mimics the stock Mastodon web app implementation.
Note: this PR rolls in the changes from an existing open PR for menu UI: #1673. If this PR is merged, #1673 can be closed as well.
> feat: Report posts

- docs/content/80.pwa.md
- modules/pwa/i18n.ts
- package.json
- pnpm-lock.yaml
This PR also includes:
- add `edge_side_panel` entry to pwa manifest: https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/sidebar#enable-sidebar-support-of-pwas-in-microsoft-edge
- add `handle_links` and `launch_handler` entries to pwa manifest to handle shorcuts links properly, rn open a new Elk client
- enabled `prefer_related_applications`
- add `related_applications` with MS Store entry
~~On draft, just for testing we've configured last 2 pwa manifest entries properly, I need to change it only when `env === 'release'`.~~
~~Still on draft, awaiting MS confirmation related apps entry is ok.~~ We'll use url from data reported by Daniel, we can check it only when released.
EDIT: I'm testing it in desktop and Android clients, maybe I need to change …
> chore: bump to pwa plugin 0.16.4

- components/magickeys/MagickeysKeyboardShortcuts.vue
Replaces incorrect reference to `cmd` key in `MagickeysKeyboardShortcuts` with proper platform key on non-macOS devices.
Old display (see _Actions -> Command mode_):
New display
> fix: Update command key in keyboard shortcuts modal

- composables/cache.ts
Per the documentation (https://docs.gotosocial.org/en/latest/api/swagger/)
we need to include the `@domain` so that the user resolved to
is unique (otherwise GtS can return accounts from different domains
sharing the same username).
Aside, from 0.10.0 GtS also provides a `/accounts/lookup` endpoint,
so we can remove this special case when it is out.
> fix: add domain when querying for user on GoToSocial

- components/nav/NavBottom.vue
fix #1422 
Hi, this is the follow-up PR of #1867
This changes the `<label>` to `<button>` so that users can focus on it and also can open the menu panel by Enter/Space key. I think this doesn't change anything visually.
I'm not sure why the original invisible `<input>` was needed for the click event (I guess it could be attached to `<label>` too?). I believe the same functionality is available now via the `<button>`'s click event so removed it.
**Before**
**After**
Ideally, we can improve the menu items by following the appropriate ARIA menu role coding guide (ARIA: menu role - Accessibility | MDN - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role) so that those who use accessibility tool can operate the menu more easily. But it requires more detailed work …
> fix(a11y): make the bottom menu button focusable and navigable with a11y label

- components/account/AccountInfo.vue
- components/search/SearchAccountInfo.vue
- components/status/StatusCard.vue
Currently on Canary there is a issue whereby the locked account indicator shows up when a account is marked as a bot. This PR resolves that issue by modifying the state to check if the account is locked.
> fix: Show lock indicator with the correct state

- composables/cache.ts
This follows #2221.
I made a bug where I added the domain into the query regardless of the original query, so it was not working when we hit an URL like `https://elk.zone/gts.example.com/user@example.com`.
I'm just doing a simple "does the query contains a `@` check" to add the domain, I wonder if it's enough.
Sorry for the last sloppy PR :pensive:
> fix: only add domain when none was provided

- components/publish/PublishWidget.vue
- components/status/StatusCard.vue
fix #1679
This was caused by autofocusing the tooltip during keyboard navigation.
A similar issue was reported in the original `floating-vue` repository (https://github.com/Akryum/floating-vue/issues/872), which is the component we use to implement the `CommonTooltip`, and the `no-auto-fucus` option was implemented as mitigation.
I found the same issue on the "created at" time label of the post.
1. Click the compose textarea
2. Use the `Tab` key several times to focus on the compose buttons and "created at" time.
3. Confirm if the focus won't be lost so the application is navigable with the keyboard.
> fix: prevent the lost of focus on compose icons

- docs/README.md
- docs/content/0.index.md
- docs/content/1.guide/1.index.md
- docs/content/2.deployment/1.netlify.md
It looks like https://docs.elk.zone/ has several image path errors like the one below.
I assume that the server URL was moved from the path `/docs/` to the current subdomain `docs.elk.zone` at some point.🙂 Simply deleting the `docs/` prefix solved the issue.
> docs: fix image URLs

- components/account/AccountHeader.vue
- components/account/AccountInfo.vue
- components/account/AccountRoleIndicator.vue
Linked to issue: https://github.com/elk-zone/elk/issues/2056
Added `AccountRoleIndicator` which is based on `AccountBotIndicator` so it has the same design. I use the color and name of the Role object to display it on the profile.
> feat: add roles into account header and info

- locales/en.json
- locales/ja-JP.json
- pages/settings/profile/appearance.vue
resolves #2263
This PR implements the error messages when saving the profile almost the same way as the publishing errors. This task has remained as TODO.
1. Go to /settings/profile/appearance
2. Upload the large icon image (>2MB)
3. Click "Save" button
You can use this large image for testing:
Source: https://svs.gsfc.nasa.gov/vis/a030000/a030800/a030877/frames/5760x3240_16x9_01p/
**Error message example**
Note: There seems a repetition in the error message but the original error message has this string and I couldn't find any other string. I guess masto.js or the server returns this string.
**Close button tooltip label**
**Current publishing errors UI (for reference)**
> feat: show save failed error messages on the profile config page

- composables/masto/publish.ts
- locales/de-DE.json
- locales/en.json
- pages/settings/language/index.vue
closes #2079 
ref: #876
ref: #1196
This PR adds the following things:
- use the users writing/posting language from mastodon profile when available
- add a link to the mastodon settings page (where the writing/posting language can be configured) to Elk language settings page
> feat: use configured writing/post language of user from mastodon

- components/publish/PublishWidget.vue
resolve #2276
You can also the alternative implementation (original flipping layout) for comparison: #2284
> feat: hide original post area in the edit widget

- components/account/AccountHeader.vue
fix #2287
To specify the correct image size, specifiers had to be applied to `AccountAvatar`, not the parent `<button>`.
Currently, Only `img { max-width: 100% }` (from the reset CSS) was applied to avatar `<img>` so it was not shown as expected if it's not the non-square image.
> fix: correct ratio of profile header avatar

- styles/global.css
Currently, elk's font-family is based on the `@unocss/reset/tailwind.css` file. The font-family in tailwind css is Mac-centric and does not take into account the Windows environment (specifically the CJK Windows environment).
The biggest problem with the font-family in tailwind css is the presence of system-ui, which breaks readability in the CJK windowing environment. In addition to breaking readability on Windows(https://infinnie.github.io/blog/2017/systemui.html), system-ui does not take advantage of the ability to change fonts based on lang attributes.
Current ELK client. Because of system-ui, it renders Malgun Gothic(This is Korean font. This is not japanese font) instead of Japanese fonts, and the Japanese readability of Malgun Gothicc is horrible.
After removing system-ui, the …
> fix: improve default font family

- components/settings/SettingsToggleItem.vue
Currently, the screen reader does not announce whether the current toggle is on or not.
The bottom text is the screen reader speech output.
Before:
After:
> feat(a11y): add checkbox role to toggle items

- components/status/StatusActionButton.vue
- components/status/StatusActions.vue
Show a disabled boost button when the toot can't be boosted.
1. lower opacity
2. replace with a repeat-off icon
> feat: disabled boost button

- components/status/StatusActionButton.vue
The button is disappeared when the post is unfavorited/unbookmarked. I think I accidentally introduced this bug in the pr #2326. Sorry for that.
https://github.com/elk-zone/elk/assets/10359255/f482d555-662e-4b1a-9b52-50e4afa1d6a5
> fix: like/bookmark button is disappeared

- components/publish/PublishEditorTools.vue
- components/publish/PublishWidget.vue
- components/status/StatusActionButton.vue
- components/status/StatusDetails.vue
- components/status/StatusSpoiler.vue
- components/status/StatusVisibilityIndicator.vue
1, announce open editor tools button & emoji button
**Before**:
**After**:
2. show "not allowed" cursor for disabled boost button
**After**
3. don't announce the midpoints between icons
**Before**
4. announce "expanded" & "collapsed" state for "show more" and "show less" buttons
5. announce the visibility of the toot when focus is moved to the visibility icon
> feat(a11y): enhance post-related a11y features

- components/publish/PublishWidget.vue
fix: https://github.com/elk-zone/elk/issues/2272
It was a wrong use of tailwind breakpoints
> fix: publish height

- components/main/MainContent.vue
> refactor: solve the problem that the title is not centered

- locales/en.json
Replaces *status* with *post* and *reblog* with *boost* for consistency.
> fix(i18n): use "post" and "boost" consistently

- components/status/StatusLink.vue
Correct status focus style if use virtual scrolling
- Before
- After
> fix: change status focus style

- components/nav/NavFooter.vue
This adds an explicit link/button to show the keyboard shortcut helper panel. I tried to implement both but that's just to evaluate which one is better (will revert one of the commits later).
I saw some people commented somewhere (sorry, couldn't find the original comment) that they didn't notice the keyboard shortcut is supported by Elk. This link/button can help to find the feature.
> feat: add keyboard shortcut helper link or button

- components/notification/NotificationCard.vue
Since I'm an admin on the instance I use, I generally am interested in who signs up. I noticed the signup notification doesn't link to the profile of the new users, and this PRs adds this behavior.
If there was a reason to not do this, or you'd want it handled differently, LMK!
> feat: make new users signup notifications link to their profile

- components/account/AccountHeader.vue
this fixes an issue where on smaller devices the avatar was moved down, not aligning with the profile header anymore
an example of the issue can be seen here: 
Fixed it looks like this:
to test the fix, you can take a look at any profile with header image and profile picture on a smaller screen ( when the profile buttons wrap around), the account I used is http://localhost:5314/bumscode.com/@tagesschau@ard.social on screen width 320px
> fix: profile header avatar being pushed lower on smaller devices

- locales/fr-FR.json
Hi folks, how are you doing? Everything is good in your life atm?
I added some french translations. 🙂
Before: `fr-FR 96.4% (529/549)`
After: `fr-FR 99.1% (544/549)`
5 still missing, but there's just one translation in Hungarian, not sure of the meaning so I'll wait for more context.
In the meantime, it's already that!
Cheers.
> feat(i18n): Update the fr-FR locale

- nuxt.config.ts
I'm checking why the PWA icons not working in production in browser devtools.
In my local works, on my Windows machine the security module not being included.
For context: https://twitter.com/kvnbsst/status/1712246451835936925
~~Draft PR, later will be removed.~~
> fix(pwa): add manifest-src to CSP

- components/common/CommonPaginator.vue
This is a PR for #2439 that adds a check for `items.length` in `CommonPaginator.vue` before setting the `endMessage` displayed in the UI.
1+ entries show `common.end_of_list` now:
<= 0 entries show the `endMessage` defined by the parent component, i.e. `common.no_bookmarks` in `TimelineBookmarks.vue`:
> fix: #2439 - `endMessage` in CommonPaginator

- locales/eu-ES.json
Added:
- 10 "authorize": "Authorize to follow",
- 11 "authorized": "You have Authorized the request",
- 41 "reject": "Reject to follow",
- 42 "rejected": "You have rejected the request",
- 44 "requested": "{0} has requested to follow you",
- 503 "embedded_media": "Embedded Media Player",
- 504 "embedded_media_description": "Display an embedded player instead of the normal preview card when expanding shared media streaming links.",
- 582 "embedded_warning": "Playing this may reveal your IP address to others.",
> fix(i18n): update Basque localisation

- composables/masto/icons.ts
Pinterest icon `i-ri:pinterest-line` 
https://github.com/elk-zone/elk/assets/108399634/e6356884-2fed-463c-ade3-6aa6e51c56d6
> feat: add pinterest icon in profile metadata

- styles/vars.css
- unocss.config.ts
#2449 switched to white for the solid button text color, that looks good on light mode but a bit off in dark mode.
See
Against
#2449 also didn't change all similar buttons (like the Follow button that had custom logic and was already using `text-inverted` so it is white text for light mode and black text for dark mode). This PR switches to using `text-inverted` everywhere.
> fix: btn-solid text color for dark mode

- components/account/AccountHeader.vue
- locales/en.json
- locales/ja-JP.json
This is one option to solve #2199. Please see the issue for details and other options.
> feat: put account name copy button

- composables/masto/icons.ts
- package.json
- pnpm-lock.yaml
This adds Threads icon support in the links of the profile page.
partially implements #2472 (only Threads icon)
> feat: support Threads icon in profile links

- components/status/StatusAttachment.vue
closes #2443
In order to avoid cover video controls, we should move `ALT` to the top for the video attachments.
From an aesthetic perspective, it doesn't seem ugly either.
> fix: move the ALT text button for video attahcments to the top

- config/pwa.ts
- modules/pwa/config.ts
- modules/pwa/index.ts
This PR includes:
- use Nuxt `nitro:build:public-assets` hook to generate the service worker: Nitro moving assets (`_nuxt/**`) and html pages after running pwa api to generate the service worker: all assets and html pages missing from sw precache manifest
- include logic to handle Nuxt Payload Extraction and App Manifest
- remove manifest transform from configuration: overriden by the configuration module
- Vite 5 support, Nuxt almost ready
Without this PR (new Nitro version with Nuxt 3.8.2 using `rollup:before` hook, `Generate public .output/public` must run before sw generation):
With this PR:
/cc @patak-dev
> chore(pwa): change sw generation logic

- components/settings/SettingsThemeColors.vue
This makes the theme color mapping work as it should IMO. The current implementation just worked because the `key` and `--theme-color-name` happen to be the same, which I think is an assumption we can't make forever.
In our skin of elk, we changed the name of a theme and it was necessary to do these changes (https://github.com/maybeanerd/crab/pull/3).
This should enable future named themes for elk in general without breaking anything.
> fix: correct linking of theme colors

- composables/masto/icons.ts
See https://github.com/elk-zone/elk/issues/2472#issuecomment-1870935481 for the original icon request from @hawkticehurst.
I chose the line style instead of the fill style to be consistent with other icons.
You can test this change on the profile edit page: https://deploy-preview-2534--elk-zone.netlify.app/settings/profile/appearance
> feat: add a new link icon

- components/status/StatusSpoiler.vue
At `Home` page, it has no contrast with pages background since they're both `base`. But at notification page, there's difference between them.
This pull request set the button as `rounded-lg` to make the button have a better appearance. But I'm not sure if the button's background should be always transparent, since it will be transparent when the post is a DM.
> fix: spoiler button style in notifications

- composables/shikiji.ts
- composables/tiptap/shikiji-parser.ts
- package.json
- pnpm-lock.yaml
Update `prosemirror-highlight` and resolve the issue below.
If you have a code block in the editor and then refresh the web page, the content in the editor will be restored. However, since the shikiji highlighter is loaded asynchronously, the code block will not be highlighted. You will need to type something to trigger the highlighter.
After updating `prosemirror-highlight` to the latest version, we can return a promise in the `useHighlighter` function. When the promise resolves, the editor will re-parse the code block automatically.
The following videos show the difference between the old and new versions:
**Before:**
https://github.com/elk-zone/elk/assets/24715727/85552eb2-0fbe-431f-932f-a1801e6c17f5
**After:**
https://github.com/elk-zone/elk/assets/24715727/1ddd21cd-62b9-44f6-8a56-a9a3 …
> fix: trigger code block highlighting when the highlighter is ready 

- app.vue
Always having elk.zone in the og:url doesn't make sense. The urls don't even work if another instance is configured
I've deployed the fix to my elk instance and it works:
```
$ curl -sSf https://elk.fosspri.de/@joshix/111711285196317734 | grep 'og:url'
<meta property="og:url" content="https://elk.fosspri.de/@joshix/111711285196317734">
```
for it to work I had to add the following to my nginx config:
```
proxy_set_header Host              $http_host;
proxy_set_header X-Real-IP         $remote_addr;
proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```
> fix: meta og:url should use the origin of the request instead of elk.zone

- locales/en.json
simply change the mention tab label to the plural form.
ref. Original report: https://discord.com/channels/1044887051155292200/1045711790593560678/1199399384463442041
> fix: rename tab label from "Mention" to "Mentions"

- components/account/AccountLockIndicator.vue
- locales/en.json
Original request: https://discord.com/channels/1044887051155292200/1045711790593560678/1132028254795087983
This allows translation of the "Lock" label.
> fix: allow to translate "Lock" string on profile

- components/publish/PublishEditorTools.vue
On mobile devices, the tooltip overlaps with the editor tool popup. Clicking on tooltip will dismiss both of them. This pr moves the editor tool popup to bottom. This looks the same as the emoji popup.
Before:
https://github.com/elk-zone/elk/assets/10359255/a8e6d9cc-fa2d-4680-9813-d02744fe27cd
After:
> fix: fix tooltip overlaps with editor tool popup on Mobile

- pages/notifications/[filter].vue
There was one missing unwrapping for the computedRef 🙂
> fix: fix `[object Object]` on the mentions tab

- components/magickeys/MagickeysKeyboardShortcuts.vue
- components/notification/NotificationPaginator.vue
- components/timeline/TimelinePaginator.vue
- locales/en.json
- locales/es.json
- plugins/magic-keys.client.ts
This should work, but I couldn't test it properly. We have an issue with the subscription to the federated stream it seems, maybe to other streams too.
> feat: . shortcut to show new items

- composables/paginator.ts
Regression from the Masto.js v6 update
There still seems to be issues with the updates. I think this was working before, but I can't seem to get updates now after subscribing.
> fix: paginator watch

- components/magickeys/MagickeysKeyboardShortcuts.vue
- locales/en.json
- plugins/magic-keys.client.ts
This PR implements most of the navigation shortcuts in #1855.
**Before**
**After**
These had already been implemented:
- g+h - Home
- g+n - Notifications
New shortcuts by this PR:
- g+c - Conversations
- g+f - Favourites
- g+b - Bookmarks
- g+e - Explore
- g+l - Local Timeline
- g+t - (Federated) Timeline
- g+i - Lists
- g+p - Profile
- / - Search (this is listed in #1856).
Remaining:
- g+u - Go to User (focus on search with '@')
> feat: add several new shortcut keys for navigation

- components/account/AccountHoverWrapper.vue
The `intersectionRatio` usage is wrong in `AccountHoverWrapper`  and so any mention in the screen will show the dialog.
This PR also prevents fetching the account when testing.
> fix(ui): account mentions not being fetched when visible

- components/publish/PublishAttachment.vue
fix #2629
I wrote the cause of the issue in #2629.
> fix: allow to edit alt description of attached image again

- package.json
- pnpm-lock.yaml
PWA plugin reverts [PR 633](https://github.com/vite-pwa/vite-plugin-pwa/pull/673)  and [PR 675](https://github.com/vite-pwa/vite-plugin-pwa/pull/675) to original register logic.
> fix(pwa): update pwa plugin to fix broken prompt

- components/status/StatusReplyingTo.vue
The reply status account is expected to be the target account but actually, it showed the reply author.
ref. https://discord.com/channels/1044887051155292200/1046769315405365288/1212694499160096858
> fix: show correct reply target user account in reply post header

- .github/workflows/ci.yml
- tests/nuxt/content-rich.test.ts
- vitest.config.ts
From time to time in my local using Node 18.16.0 LTS vitest cannot finish the worker, when using Node 20.10.0 LTS tests seems to be fine: CI using Node 18.19.1.
The error on my local is about flushing local storage on user.ts module and the write method via the pausableWatcher in `@vueuse/shared` and so I just mock it, adding also indexedDB and intersectionObserver mocks from nuxt test utils.
EDIT: executed CI 3 times and seems to be fine
> chore(tests): fix vitest can't terminate worker

- components/account/AccountHoverCard.vue
- components/account/AccountHoverWrapper.vue
This PR includes:
- fetch account data when hovering on the account link (on demand)
- ~~add status card skeleton when resolving the account data~~
This will also prevent fetching account data of all accounts in the viewport while scrolling.
We can change the skeleton or switch to use an spinner loader.
Check this video https://streamable.com/4kk87e : added few seconds timeout to see the skeleton on first fetch (afterwards it is immediate)
/cc @patak-dev @shuuji3
> feat(ui): fetch account data on demand

- composables/tiptap.ts
Updating tiptap seems to break the mention "plugin" (added data-type and data-id to the span)
> fix(ui): mentions not working when composing

- components/nav/NavBottom.vue
- components/nav/NavSide.vue
- components/timeline/TimelineNotifications.vue
- constants/index.ts
fix #1058
This allows Elk to remember the last accessed tab including filters like "Favorite" and "Reblog", not only the "Mentions" tab.
1. Navigate to the "Notification" page.
2. Select the "Mentions" tab or any other filters.
3. Move to the other page.
4. Navigate to the "Notification" page again.
5. See if the previous tab is shown (not the default "All" tab).
> fix: remember last accessed notification tab

- components/nav/NavBottom.vue
- components/nav/NavSide.vue
- constants/index.ts
- pages/[[server]]/explore/index.vue
- pages/[[server]]/explore/links.vue
- pages/[[server]]/explore/tags.vue
- pages/[[server]]/explore/users.vue
This is similar functionality to #2654 but for the Explore tab.
You can test in the same way as the Notification tab.
> feat: remember last accessed explore tab

- components/nav/NavSideItem.vue
- composables/screen.ts
fix #2656 
Adopted the same hover highlight style as the bottom two items like the Zen mode menu.
In dark mode, the highlight was really hard to see:
> fix: consistent hover highlight styling in mobile bottom navigation menus

- components/account/AccountMoreButton.vue
- components/common/CommonCheckbox.vue
- components/list/ListEntry.vue
- components/modal/DurationPicker.vue
- components/modal/ModalConfirm.vue
- components/status/StatusActionsMore.vue
- composables/dialog.ts
- composables/masto/relationship.ts
- locales/en.json
- types/index.ts
resolve #2301
This PR adds the two mute options in the confirm dialog for muting.
I set the default duration setting as 1 hour (this can be changed if the other value is better), and the mute notifications enabled, which is the current default.
disables the "Mute" button
To implement this feature, I adjusted the existing `ConfirmDialog` component to be able to show mute-related options and return selected information. (4276b50d49caf59252c5db0fd9c8bb0e6c49028e cca244ad12b56ac58173113cec38d458a5109a95)
Also, I implemented the `DurationPicker` component (ee0742e7701cf0d703b8e50aa4297fa8fd241581), where we can select minutes with 5 minutes step. I chose a 5-minute step for the minutes input to make it easier to select, but users can input any minute value type by directly typing.
Another …
> feat: allow to set mute duration and notifications mute option

- composables/masto/relationship.ts
fix #2668
There were two cases missed by the current implementation:
1. Mastodon relationships API accepts batch requests for multiple IDs (ref. https://docs.joinmastodon.org/methods/accounts/#relationships) but it does not always ensure the order of returned relationships. For example, when we requests for `[id1, id2]`, the response can be `[relationship2, relationship1]`. 
1. when there's an issue with fetching the relationship for some accounts, the response array omits those accounts in response. For example, the request `[id1, id2, id3]` can result in the response `[relationship1, relationship3]`.
This fix ensures using only returned relationships and updating the correct corresponding relationship data with the same ID.
I inserted the following logs here to see how the relationship …
> fix: fix incorrect follow status on followers and following pages

- composables/masto/search.ts
fix #2675
This was caused by another missing `.value` 😅
> fix: prevent empty search keyword to send invalid request

- package.json
- pnpm-lock.yaml
probably fix #2628
There was an GitHub Issue for `useActiveElement` in the `@vueuse/core` repository, which was fixed by the latest version `10.9.0`: https://github.com/vueuse/vueuse/issues/3799.
We are using almost the same logic for our keyboard shortcuts here: https://github.com/elk-zone/elk/blob/edcc8741bfe63302ae1ba58886ccd7279115e345/plugins/magic-keys.client.ts#L10-L18
Also, confirmed this issue was fixed: https://github.com/elk-zone/elk/pull/2612#issuecomment-1962390478
> chore: upgrade `@vueuse/core` from `10.8.0` to `10.9.0`

- components/command/CommandPanel.vue
- components/list/ListEntry.vue
- components/modal/ModalConfirm.vue
- components/user/UserSignIn.vue
- composables/masto/search.ts
- composables/push-notifications/usePushManager.ts
- pages/[[server]]/@[account]/[status].vue
- pages/notifications.vue
- pages/notifications/[filter].vue
see #2678 for how to temporarily enable some vue-related ESLint rules
> fix: fix `vue/no-ref-as-operand` and `vue/return-in-computed-property` ESLint errors

- composables/tiptap.ts
Updating tiptap seems to break the hashtag "plugin" (added data-type and data-id to the span), similar problem wth mentions plugin in #2655
> fix(ui): hashtags not working when composing

- package.json
- pnpm-lock.yaml
`Intellij IDE`:
`nr lint`
closes #2678
> chore: bump to eslint-config to 2.8.1

- .github/workflows/docker.yml
resolve #2682
Takahē has a quite similar GitHub Actions recipe and it supports `arm64` container (I can run Takahē on Raspberry Pi): https://github.com/jointakahe/takahe/blob/main/.github/workflows/docker-release.yml#L45.
This PR added `linux/arm64` to the platform parameter during the Docker build.
I tested the produced containers in my repository (https://github.com/shuuji3/elk/pkgs/container/elk/190033880?tag=main) both on Raspberry Pi 4 and Apple Silicon macOS and both seem to be working well.
Here's the result of running on Raspberry Pi 4:
```shell
ubuntu@pi-0:~$ hostnamectl
Static hostname: pi-0
Icon name: computer
Machine ID: 3b5684e503b04b088f70fa1fde008fee
Boot ID: 6661a882e73c4ac59797c63fabbe919b
Operating System: Ubuntu 22.04.1 LTS              
Kernel: Linux 5.15.0-1044-raspi …
```
> ci(docker.yml): support `linux/arm64` container

- styles/global.css
fix #2590 
Ensure the `pre` tag style is not overwritten by the user agent stylesheet. The default value was set to `pre`.
> fix: pre tag overwritten by default style

- components/notification/NotificationCard.vue
mitigates #2701 #2043
The current error message seems to be for development and does not provide a good UX for normal users, especially those who receive reaction emojis frequently.
So instead of showing error messages, this change will only output warning messages to the console for the known two emoji reaction types: `pleroma:emoji_reaction`, `reaction`. (Other unknown notification types will keep showing the same error messages.)
Elk could support the Emoji reaction notification in some form in the future. (Note: currently, masto.js does not provide these non-Mastodon notification type information / related to https://github.com/neet/masto.js/issues/939)
> fix: prevent showing notification errors for dev for known emoji reaction types

- components/timeline/TimelinePublicLocal.vue
Now the `load new items` button is currently not visible due to being associated with the wrong stream.
> fix: correct local timeline stream

- docs/nuxt.config.ts
- locales/es.json
We've some hydration missmatch in docs: this PR includes `scule` in `vite.optimizedDeps.include`, accessing `/guide/contributing` page Vite optimizing `scule`.
/cc @mrcego @patak-dev
> feat(i18n): add missing spanish mute duration dialog entries

- package.json
- pnpm-lock.yaml
resolves #2705
simply updating from v6.5.2 to v6.7.0. I think no change affects Elk feature.
ref. masto.js release note: Releases · neet/masto.js - https://github.com/neet/masto.js/releases
> chore: update masto to v6.7.0

- plugins/magic-keys.client.ts
Currently, opening command panel with shortcuts `cmd+/` will navigate to search page as well.
This pr adds `computed(() => keys.current.size === 1)` to ensure other key combinations will not accidentally trigger this shortcut.
before:
https://github.com/elk-zone/elk/assets/10359255/ab6fae31-0308-4fe4-8726-89d5dbc1855a
after:
https://github.com/elk-zone/elk/assets/10359255/e5c68193-ed53-48b5-882f-705fd3f99c18
> fix(ui): prevent from navigating to search page when opening command panel

- components/publish/PublishWidget.vue
The removed options are assigned to `options` by mistake.
before:
https://github.com/elk-zone/elk/assets/10359255/840e2c85-b345-494a-a796-bd83754ddcbd
after:
https://github.com/elk-zone/elk/assets/10359255/b13ecbdd-d19e-479d-b408-8b4daa15b6d3
> fix(ui): wrong polls are removed

- composables/command.ts
`Settings` is duplicated in the command panel.
The other one has been defined in NavSideItem.vue
https://github.com/elk-zone/elk/blob/f6f50a582e94f56ecb8b376e5c9213b724b04a50/components/nav/NavSideItem.vue#L19
before:
after:
> fix(ui): remove a duplicated command

- components/publish/PublishWidget.vue
- components/search/SearchWidget.vue
- pages/[[server]]/search.vue
This PR contains two improvements for keyboard navigations:
- [fix: allow to escape from compose editor and search input by esc key](https://github.com/elk-zone/elk/commit/4c2e38adb1229e3fad8fac673fa070893b55f5e0)
- [fix: allow focus to search input within search page](https://github.com/elk-zone/elk/commit/08a8ab62c6adad3cab0d9bfae21f663d18991c8a)
The first one is to allow using the ESC key to unfocus the editor and search inputs. 
This is the default behavior for the native HTML input/textarea elements so users expect that the ESC key works as usual, but Elk uses the custom elements that prevent navigating with the ESC key and it needs to use the Tab key to go to outside input.
The second one is to fix the behavior of `/` key in the search page.
When typing `/` in other pages than the …
> fix: improve keyboard operability especially on search page and editor

- components/status/StatusActionsMore.vue
- components/status/StatusDetails.vue
When enabled in the zen mode, the more actions menu shows the hidden action items such as "Reply" and "Boost". However, in the details page, the action footer is shown by default so we don't have to include these items in the more actions menu.
This PR hides these items only within the details page. The items in the home timeline remain the same.
No bottom actions so the more actions menu has items.
Both the bottom actions footer and the more actions menu has the same set of items, which are duplicated.
> fix: hide duplicated status actions items on details page in zen mode

- locales/en.json
- pages/settings/language/index.vue
Currently, the language translation status only shows the percentage number of the translation status and it's a bit unclear which text is not translated and where to find the Elk documentation.
This will also help potential new translators find the entry point for contribution. 
Japanese example:
> feat: add "How to contribute?" link next to language status

- components/nav/NavUser.vue
Currently, the sign-in button has the icon for both the single server instance and the actual button on the sign-in dialog.
So I feel like it's natural that the default sign-in button also has the sign-in icon on the button rather than the simple text-only button.
> feat: put sign-in icon to default "Sign in" button

- components/status/StatusLink.vue
Clicking on emoji does not navigate to status detail page
Before:
https://github.com/elk-zone/elk/assets/10359255/c5255d95-3e69-479e-99b6-366764d8500b
After:
https://github.com/elk-zone/elk/assets/10359255/1066c285-e45a-48b9-bed2-98e248a07ac9
> fix(ui): clicking on custom emoji does not navigate to status detail

- styles/global.css
blockquote is common in Misskey and some mastodon instances with markdown plugins
Probably fix #1502 
[demo post](https://dvd.chat/notes/9rie8zfeiusszl45)
> feat(ui): style blockquote

- components/common/CommonPaginator.vue
- components/notification/NotificationPaginator.vue
- composables/paginator.ts
Fixes #2724
#2714 tried to fix an issue introduced at #2530 and #2566.
I removed `eventType` in #2566 from paginator assuming that now the events were normalized as `'update'` given that we are subscribing to specific streams. The event for the notification stream is still `'notification'`. This PR adds back `eventType`.
> fix: notifications in update timeline

- components/modal/ModalMediaPreviewCarousel.vue
- components/status/StatusAttachment.vue
- composables/settings/definition.ts
- locales/en.json
- pages/settings/preferences/index.vue
1. add `gif` indicator on gif media
2. clicking on `gif` can also enable the media preview dialog
example posts:
https://deploy-preview-2752--elk-zone.netlify.app/universeodon.com/@elkdev/112211964228804763
https://elk.zone/o3o.ca/@rikan@m.otter.homes/112061227739128715
https://elk.zone/mastodon.ktachibana.party/@furretya/112210841006362590
Before
https://github.com/elk-zone/elk/assets/10359255/d0424fff-6331-4185-bc16-3077b520d44e
After:
https://github.com/elk-zone/elk/assets/10359255/6742877e-4f1a-40b8-9a7e-1e4de4eca4e4
> feat(ui): improve gif support

- components/modal/ModalMediaPreview.vue
Not sure why both `w-full`(width: 100%) and `w-100vh`(width: 100vh) are applied to media preview card. Sometimes, `w-100vh` are overriding `w-full` on my devices, making the picture misaligned.
Plus, I guess `w-100vh` is a typo? Is it supposed to be `w-100vw`?
> fix(ui): media preview card is misaligned

- components/settings/SettingsToggleItem.vue
Check dev server, w-full is before w-fit, sometimes the styles are reversed and the toogle items don't fill the full width:
> chore(ui): use full width in settings toggle items

- .github/workflows/ci.yml
It looks like the CI testing is still sometimes running 6 hours: https://github.com/elk-zone/elk/actions/workflows/ci.yml?page=3#:~:text=4%20days%20ago-,6h%200m%2023s,-ci
Until the complete fix, this adds the testing timeout to 10 minutes to reduce the waste of computing resources. Usually, it will end within 1 min 30 seconds so 10 minutes should be a safe limit.
> ci(ci.yml): limit maximum execution time of ci test

- components/account/AccountBotIndicator.vue
- components/account/AccountFollowRequestButton.vue
- components/account/AccountHeader.vue
- components/account/AccountHoverWrapper.vue
- components/account/AccountLockIndicator.vue
- components/account/TagHoverWrapper.vue
- components/common/CommonRouteTabs.vue
- components/common/CommonTooltip.vue
- components/list/Account.vue
- components/list/ListEntry.vue
- components/publish/PublishWidget.vue
- components/status/StatusCard.vue
- pages/[[server]]/lists.vue
- tests/nuxt/__snapshots__/content-rich.test.ts.snap
This PR removes all `no-auto-focus` attributes from `CommonTooltip` component usages, adding also `no-auto-focus` in `VMenu` and `CommonTooltip` to disable it to fix losing focus when using the keyboard.
Without this PR, check the video or open elk.zone and traverse the app using the tab key: https://streamable.com/5lngi3
With this PR: https://streamable.com/c0jpsj
> fix(ui,a11y): focus lost when navigating using the keyboard (tab)

- components/notification/NotificationGroupedFollow.vue
The name is highlighted and so I assume this is supposed to be clickable.
> fix(ui): make display name clickable in grouped follow notification

- components/publish/PublishWidget.vue
fix #2781
Due to the regression, the editor has been expanded without condition. This change prevents the expansion by default and keeps the lower height until clicking.
> fix(ui): fix regression where editor is expanded before composing

- components/list/ListEntry.vue
Before: 
https://github.com/elk-zone/elk/assets/10359255/88fcb9b9-5b4b-4dcd-85c3-47e8a389633c
As you can see from this screenrecord, the name is always out-of-date.
After:
https://github.com/elk-zone/elk/assets/10359255/6116f959-6e2e-4c84-bb19-42d83788f282
CommonPaginator triggered updateEntry once a new list value is assigned.
https://github.com/elk-zone/elk/blob/706cffe209293478c84ed529fedbbd94b4d1dec0/components/common/CommonPaginator.vue#L60-L64
The cancelEdit will trigger a `reset` but at that time, `list.value` is still holding an old value. This pr just moves the `reset` after nextTick to ensure the value is up-to-date.
https://github.com/elk-zone/elk/blob/706cffe209293478c84ed529fedbbd94b4d1dec0/components/list/ListEntry.vue#L43-L46
> fix: list name is not up-to-date after modification

- components/settings/SettingsFontSize.vue
- pages/settings/interface/index.vue
When using the keyboard we don't know if the font size is focused:
> feat(ui): add font size outline when focused

- components/settings/SettingsBottomNav.vue
> fix: remove nav buttons from initial selection on setting page

- locales/en-GB.json
There are several missing UK spellings in the `en-GB.json` file.
This PR includes the following (there might be others):
- authorize -> authorise
- favorite -> favourite
- anonymize -> anonymise
- color -> colour
- optimize -> optimise
- decentralize -> decentralise
Checked with Cambridge Dictionary (example: https://dictionary.cambridge.org/dictionary/english/decentralize)
> feat(i18n): update en-GB localization

- components/status/StatusMedia.vue
fix #2502
fix #2796
This PR fixes the broken grid layout for more than 4 attachments. In that case, the number of the grid columns switches from 2 to 3 to reduce the height of the post and show more overview of the gallery.
Example posts in https://github.com/elk-zone/elk/issues/2796: https://pixelfed.social/p/Lacalle/684124192137313050
> feat: support more than 4 media attachments with 3 columns grid

- components/settings/SettingsBottomNav.vue
- components/settings/SettingsColorMode.vue
- components/settings/SettingsFontSize.vue
- components/settings/SettingsThemeColors.vue
- pages/settings/interface/index.vue
This PR also includes a missing `:` in the webkit-slider-runnable-track style (L72 in SettingsFontSize sfc): 
`input[type=range]:focus:-webkit-slider-runnable-track` =>`input[type=range]:focus::-webkit-slider-runnable-track`
/cc @patak-dev @shuuji3  We should also review all settings, rn each setting entry with custom layout: check language and preferences.
We should:
- add semantic markup to preferences settings: include sections + h2
- add semantic markup to languages settings: include sections + h2
- unify styles: section + h2 and use CommonCheckbox or SettingsToggleItem for checks (h2 in some settings using font large with custom paddings/margins...)
- change markup to middle settings panel to aside
> feat(a11y): add semantic markup to interface settings

- components/list/Lists.vue
- locales/en.json
Fix #2819 
The implementation is to replace the end message with a styled button, which navigates to `[[server]]/lists`
> feat(ui): add manage list at the end of the lists

- components/status/StatusContent.vue
|Before|After|
|--|--|
|<img width="618" alt="Screenshot 2024-04-20 at 11 48 12 AM" src="https://github.com/elk-zone/elk/assets/10359255/8364aa33-dac1-4ccf-bbea-b0ed8c5f3fef">|<img width="613" alt="Screenshot 2024-04-20 at 12 05 23 PM" src="https://github.com/elk-zone/elk/assets/10359255/cbf9eab4-bb7b-4f57-ad1e-6c9c936ab6b9">|
Before: [Link to the post](main.elk.zone/universeodon.com/@iamada@tech.lgbt/112304940629697112).
After: [Deploy Preview](https://deploy-preview-2836--elk-zone.netlify.app/universeodon.com/@iamada@tech.lgbt/112304940629697112)
> fix(ui): show custom emoji in spoiler text

- pages/settings/preferences/index.vue
This PR also fixes invalid html markup inside the heading (h2), cannot use div inside.
@shuuji3 can you check it with VoiceOver? The section headers should be displayed (I haven't installed NVDA on my laptop and my Mac is still hijacked by my nephew)
> feat(a11y): add semantic markup to preference settings

- components/modal/ModalContainer.vue
fix #2834
The layout is off due to the change during thread implementation. This dialog was not assumed to have multiple widgets either.
Note: This publish dialog can be opened by typing <kbd>c</kbd> key.
> fix(ui): fix publish dialog layout

- locales/es.json
I guess that entry is wrong, there is nothing to preview, it should be something like "Open image in carousel dialog" or similar.
Clicking on any image will open the carousel where we can zoom or navigate between images in the toot.
/cc @patak-dev @mrcego
> feat(i18n): add `open image preview dialog` spanish translation

- .npmrc
like in vite, set package-manager-strict to false so pnpm v9 can locally be used
> chore: set package-manager-strict to false

- components/magickeys/MagickeysKeyboardShortcuts.vue
- locales/en.json
- plugins/magic-keys.client.ts
resolves `j`/`k` navigation part of #1858
> feat: keyboard status navigation with `j`/`k`

- README.md
this adds our deployment of elk to the list of community deployments
Not sure if it's okay, as it's a soft fork and not vanilla elk, but I thought It'd be nice to show that you can even deploy a slight variation of elk without much effort
> docs: add crab.bumscode.com to list of community elk deployments

- CONTRIBUTING.md
The contributing docs reference Node and PNPM versions that are no longer used by Elk:
- Node v16 should be Node v20
- PNPM v7 should be PNPM v9
Those versions were last updated on Elk by:
- Node v20: #2501
- PNPM v9: #2908
> docs(contributing): update node and pnpm version

- nuxt.config.ts
- plugins/color-mode.ts
On my iPhone, with a PWA, the status bar is always white, which makes it unreadable in white mode.
In this PR, I try to get this to work with the selected theme.
Because I don't know how to debug it differently, I'll use the hosted PR example to test.
Closes #2384
> fix(ui): change apple app status bar style

- components/notification/NotificationGroupedLikes.vue
fix #2855
Multiple avatar icons are now overlapped to reduce the area:
(dummy accounts are used in screenshots)
And the below icon will get to the front when it is hovered or focused:
Also, when there are many more accounts, it will be wrapped to the next row.
> feat(ui): overlap multiple account icons in notification

- components/status/StatusCard.vue
When focusing on the status, the horizontal line between statuses was above the focus indicator.
The keyboard navigation (currently implementing) always shows the border so this is especially noticeable.
> fix(ui): fix z-index of horizontal line between statuses

- components/main/MainContent.vue
- components/search/SearchWidget.vue
- components/status/StatusEmbeddedMedia.vue
fix #2847 by adjusting z-index values
> fix(ui): adjust z-index of Embedded Media Player and sticky header

- components/account/AccountHeader.vue
- components/account/AccountHoverCard.vue
- components/account/AccountInfo.vue
Fixes the UI issue with the profile name getting cut off when the user has roles.
On the bottom-left profile card, the roles UI was moved to be below the username.
It _could_ be in-between the name and username, but because this is a list of roles, for some users that list would look better as the last list item.
For this taller profile info card, the avatar was centered. `AccountHoverCard.vue` originally was not using the `hoverCard` prop on `AccountInfo.vue`, this was added since the hover card has the space to show roles inline with the profile name.
Before:
After:
The hover card remains untouched since it has the extra space:
Mobile:
Multiple users:
fixes: #2914
> fix(ui): profile name gets cut off by roles

- .github/renovate.json5
- modules/pwa/runtime/types.d.ts
- package.json
- patches/@vueuse__motion.patch
- patches/nuxt.patch
- patches/pinceau.patch
- patches/vue-i18n.patch
- pnpm-lock.yaml
This addresses some type issues introduced by augmenting `vue` vs `@vue/runtime-core`.
Some patches are made locally in advance of merging upstream:
- `@vueuse/motion` - https://github.com/vueuse/motion/pull/217
- `pinceau`
- `vue-i18n` - https://github.com/intlify/vue-i18n/pull/1888
- `nuxt` - https://github.com/nuxt/nuxt/pull/28542
> chore: bump and patch dependencies to augment `vue`

- components/modal/ModalConfirm.vue
- components/tiptap/TiptapEmojiList.vue
- components/tiptap/TiptapHashtagList.vue
- components/tiptap/TiptapMentionList.vue
This PR removes redundant imports from several components to improve code cleanliness and maintainability.
- Removed `DurationPicker` import from `ModalConfirm.vue`
- Removed `CommonScrollIntoView` import from:
- `TiptapEmojiList.vue`
- `TiptapHashtagList.vue`
- `TiptapMentionList.vue`
These imports are unnecessary due to Nuxt's Auto Import feature, which automatically imports components.
Keeping our codebase clean and free of unused imports helps improve:
1. Code readability
2. Maintainability
> refactor: remove redundant imports

- components/timeline/TimelineHome.vue
This reduces the limit for timeline post to 10 when used on slow connection
with this change:
without this change:
> perf: reduce timeline limit on slow connection

- styles/global.css
https://github.com/nuxt/nuxt/issues/26637#issuecomment-2035736522
EDIT: we can add a custom loading indicator, it disappears ~1 second after the page is loaded...
/cc @danielroe in your local you can test the weird behavior, if you switch to slow 3G and navigate to a not loaded page
> fix(ui): add loading indicator

- components/publish/PublishWidgetList.vue
- pages/[[server]]/@[account]/[status].vue
This PR removes the warning in `PublishWodgetList` SFC about `class` attribute: https://github.com/elk-zone/elk/pull/2946#pullrequestreview-2297350986
(there was another warning about `@published` listener: maybe the cause some publish not being refreshed once published)
I have no idea if we should add `class` attr to all entries: `@published` should
> fix(ui): bind attributes to `PublishWidgetList` list

- components/publish/PublishWidget.vue
- components/publish/PublishWidgetList.vue
This PR builds the composer in the list sfc and pass it to each widget: the widget will use the provided or build a new one composer depending on the new optional `thread-composer` prop.
(fixes the vue setup warning from this https://github.com/elk-zone/elk/pull/2946#pullrequestreview-2297350986)
@patak-dev @danielroe @shuuji3 I didn't did anything about the composer logic, maybe you can help me to test this PR properly
> fix(ui): generate only one thread composer in `PublishWidgetList` and provide it to each widget

- config/pwa.ts
- modules/pwa/index.ts
- pages/settings/about/index.vue
- public/sw.js
- service-worker/elk-sw.ts
This is related to #2970 , we will need to:
- remove old service worker
- install a new service worker
Since any client still being controlled by old service worker, the UI is missing and the new service worker cannot be activated (once installed), it will be awaiting to be activated. The user should reopen the browser and visit elk again to activate the new service worker (since we don't have the UI the user maybe close the browser before the new sw is installed and so the problem still there).
I'm going to remove the current  service worker and install a new one: https://vite-pwa-org.netlify.app/guide/unregister-service-worker.html#custom-selfdestroying-service-worker
> fix: add new service worker

- composables/users.ts
Side effect added in #2970: we need to await initial load from the setup users plugin (sorry :cry:  )
closes #2972
> fix: prevent reloading page

- locales/de-DE.json
I found a few more German translations that have been created without considering the context. There are also a few consistency changes here, and for the `embedded_warning` translation it’s just a better formulation.
> fix(i18n): Fixed some German out-of-context translations

- components/nav/NavBottom.vue
- components/nav/button/Bookmark.vue
- components/nav/button/Compose.vue
- components/nav/button/Favorite.vue
- components/nav/button/Hashtag.vue
- components/nav/button/List.vue
- components/settings/SettingsBottomNav.vue
- composables/settings/definition.ts
In the previous PR #2761 for the customizable bottom nav bar, I added several buttons but there remain several buttons in the main nav bar. This PR allows users to choose the remaining 6 buttons:
- favorites
- bookmarks
- compose
- lists
- hashtags
> feat: add 6 new bottom nav buttons

- components/settings/SettingsBottomNav.vue
fix #2805
Adjusted spacing for a narrow viewport.
Also, I removed `<button>`-related attributes since we don't need to click the button in the preview.
> fix(ui): fix and adjust bottom navigation preview on setting page

- components/timeline/TimelinePaginator.vue
- locales/de-DE.json
- locales/en.json
See https://elk.zone/universeodon.com/@test, the text “No posts here!” will currently show up even if your interface language is non-English. This text cannot be translated.
This PR makes it translatable, which can be tested in German.
> fix(i18n): Allowed translating "No posts here" text

- config/env.ts
Running `pnpm nuxt prepare` currently fails for me:
```
ERROR  fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
That’s because the directory in question isn’t a Git repository.
Running from a Git repository or even having Git installed shouldn’t be a requirement. With my change errors originating from Git are ignored. The potential impact is negligible.
> fix: Do not require Git for development

- components/notification/NotificationPaginator.vue
Steps to reproduce are in https://github.com/elk-zone/elk/issues/2216#issuecomment-2424229983. This fixes #2216 and #2889.
The issue here is function `groupItems` issuing identical IDs for different objects. In the first update it creates a `GroupedLikeNotifications` instance with ID `grouped-0`. Then we get a second update, and it again creates a `GroupedLikeNotifications` instance with ID `grouped-0`. Since both have the same key, Vue attempts to reuse the existing node for the new object. It replaces the existing `vnode` in `StatusBody` by one that belongs to a different status, and it fails miserably updating the display. So we get a correct internal structure but a completely messed up display. The solution is using a global ID counter, so that this function never re-issues the same …
> fix(ui): Avoid duplicate IDs for grouped notifications

- styles/global.css
> feat: support wider emoji

- composables/content-parse.ts
Finds all HTML tags immediately following a line break (e.g., `\n<div>`) with a regular expression and removes those line breaks, making the HTML output more compact and removing unnecessary whitespace characters. 
fix #3032
> fix: remove extra margins before tags

- docs/tokens.config.ts
Upstreaming from https://github.com/nimbus-town/nimbus/pull/34
Using light primary color in #3062
<details>
<summary><i>light</i></summary>
_light_
</details>
<details>
<summary><i>dark (not changed)</i></summary>
_dark (not changed)_
</details>
> docs: add primary light theme to fix color contrast

- components/timeline/TimelinePublicLocal.vue
This ensures the public local timeline has a consistent view as other timeline views such public timeline and user account timeline.
public timeline
https://github.com/elk-zone/elk/blob/6c5bb83ac32aecb5868a0e47ed9bcd2195a9d706/components/timeline/TimelinePublic.vue#L13
user account timeline
https://github.com/elk-zone/elk/blob/4caa63e84fd3fee4a8f3b4491a05d222fc3be3e5/components/timeline/TimelineHome.vue#L19).
> fix: apply missing reordering to local public timeline

- components/notification/NotificationCard.vue
- add support for 'annual_report' notification type
- output warning message to console instead of showing red message (see #3077)
The new notification will be rendered like this:
```html
<article flex="" flex-col="" relative="" hover:bg-active="" border="b base">
<div flex="" p4="" items-center="" bg-shaded="">
<div i-mdi:party-popper="" text-xl="" me-4="" color-purple=""></div>
<div class="content-rich">
<p> Your 2024 <a href="/tags/Wrapstodon" class="">#Wrapstodon</a> awaits! Unveil your year's highlights and memorable moments on Mastodon! </p>
<p><a href="https://mastodon.social/notifications" rel="noopener noreferrer" target="_blank">View #Wrapstodon on Mastodon</a></p>
</div>
</div>
</article>
```
The summary panel seems to be rendered within Mastodon's client and there is no URL …
> feat: support 'annual_report' notification type

- components/publish/PublishWidget.vue
This will add `disabled` attribute to actually disable the publish button when condition is met (e.g., post exceeds server char. limit). Previously we only had `aria-disabled`.
discovered with issue: #3068
> feat(ui): disable publish button

- components/settings/SettingsBottomNav.vue
When setting BottomNav menu entries, the space showing which NavButtons are currently shown is always blank. It is not showing the current saved selection neither the base defaults.
> fix: MenuBottom settings are always empty

- components/nav/button/MoreMenu.vue
The BottomNav more menu is not working on mobile view. Affecting the defineModel return value to a const allows to solve this issue
> fix: more menu is not opening on click

- composables/content-render.ts
- tests/nuxt/__snapshots__/content-rich.test.ts.snap
> fix(rtl): replace ellipsis span anchor content with bdi

- server/utils/shared.ts
I think here `await` is unnecessary though it will work. But in the previous function `deleteApp` the loop is done without `await`. So I think for consistency, we may remove `await` here.
> chore(utils): remove unnecessary `await`

- components/status/StatusPreviewCardMoreFromAuthor.vue
- components/status/StatusPreviewCardNormal.vue
fix #3139
Example: https://deploy-preview-3141--elk-zone.netlify.app/universeodon.com/@FediTips@social.growyourown.services/113709011741256464
It seems that universedon.com hasn't updated Mastodon to the latest version yet so you need to log in another account with the latest Mastodon such as mastodon.social.
> style: fix broken layout "more from" badge in card with square image

- components/notification/NotificationGroupedFollow.vue
- locales/en.json
> feat: bluesky-style follow notification

- components/status/StatusPreviewCardMoreFromAuthor.vue
fix #3155
- Remove the hover color similar to the light theme
- Remove the extra padding. This was necessary not just for hovering, but the focus border also overflowed on the left side.
https://deploy-preview-3157--elk-zone.netlify.app/mastodon.social/@Mastodon/113820526480156595
https://deploy-preview-3157--elk-zone.netlify.app/mastodon.social/@Mastodon/113820526480156595
> fix: remove extra padding and hover effect on dark theme

- package.json
creating PR as I couldn't take a shortcut for the branch protection rule:
```
[elk-release]  main (3902bac🔖 v0.16.0) [⇡] is 󰏗 v0.16.0 via  v20.18.1 󱇶 shuuji3 ⏱ 3s 
> git push
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: 
remote: - Changes must be made through the merge queue
remote: 
remote: - Required status check "ci" is expected.
To https://github.com/elk-zone/elk.git
! [remote rejected]   main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/elk-zone/elk.git'
Done
```
> chore: release v0.16.0

- pages/[[server]]/@[account]/index/index.vue
When visiting someone's account page, the page's title shows "Posts" (here "messages" in french) 
Using `nav.profile`  instead of  `account.posts` to show "Profile"
> fix: account profile page title

- components/status/StatusPoll.vue
- locales/en.json
- locales/fr-FR.json
Add an "update poll" option on polls to retrieve the latest results 
The refresh icon is animated during loading
> feat: update poll

- netlify.toml
This PR will set a new redirect from `code.elk.zone` to the GitHub repository page, for easy sharing.
> feat: redirect code.elk.zone to github repository

- components/account/AccountAvatar.vue
Account avatar are stretched instead of being centered and cropped both on profile page and avatar in status 
Before
After
> fix: account avatar should not be streched

- composables/masto/status.ts
This PR changes `Object.assign(status, newStatus)` in `toggleStatusAction` to `Object.assign(status.value, newStatus)` because `status` is a ref. This ensures that the new status is updated properly after calling `fetchNewStatus`.
> fix: update `status` ref to use `status.value`

- components/modal/ModalConfirm.vue
fix #3022
The cause was just the change of auto-imported component name.
> fix: mute duration picker was missing

- server/cache-driver.ts
- server/utils/shared.ts
Currently, the vapid key in AppInfo (needed for push notification) is retrieved from the response of `POST /api/v1/apps` and stored permanently to the server storage, when someone first tries to log in to the server from the Elk. But it was deprecated since Mastodon v4.3.0 (ref. https://docs.joinmastodon.org/methods/apps/#create). This change uses the recommended `GET /api/v2/instance` value.
This also updates the key of the storage for AppInfo (`servers:v3:${server}:` -> `servers:v4:${server}:`) because some (non-Mastodon) servers may return different values with this change. As a side effect, this will partially solve the existing lock-out issue (ref. #3150).
Mastodon server returns the exact same vapid key value from `POST /api/v1/apps` and `GET /api/v2/instance`, so there should not …
> feat: adopt to `/api/v2/instance` to fetch app `vapid_key`

- components/status/StatusAttachment.vue
- composables/settings/definition.ts
- locales/en.json
- pages/settings/preferences/index.vue
resolve #3216
Currently, Elk always mutes all videos. This PR adds a new preference to allow users to choose to unmute videos by default.
> feat: add new preference to unmute videos by default

- components/notification/NotificationCard.vue
- components/notification/NotificationGroupedFollow.vue
- components/notification/NotificationGroupedLikes.vue
resolve #3214
- Used the same timestamp formatting function as the post timestamp.
- In the following screenshot, `・2w`, `・3w`, `1min`, and `just now` parts are added.
> feat: show notification timestamp

- server/utils/shared.ts
ref. https://discord.com/channels/1044887051155292200/1346262414886178826
The `vapid_key` property was only available on Mastodon v4.3+.
> fix: handle v2 instance property correctly for mastodon v4.2 or lower

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
follow up of #3227
- This makes sure the same version of Node.js in Workflows
- Update docs
> ci: refer `.npmrc` to ensure using consistent node version

- components/notification/NotificationCard.vue
- components/notification/NotificationGroupedFollow.vue
- components/notification/NotificationGroupedLikes.vue
> fix: make notification timestamp gray and use `<time>` tag

- CONTRIBUTING.md
- README.md
- docs/components/global/TranslationState.vue
- docs/content/1.guide/3.contributing.md
I paused the codeflow app a while ago, but didn't remove the links to it in the guides. This PR removes these references as currently codeflow isn't working correctly for Elk.
> chore: pause codeflow

- composables/misc.ts
`navigator.platform` is deprecated. (https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform)
> chore: use `navigator.userAgent` instead of `navigator.platform`

- components/timeline/TimelineHome.vue
- components/timeline/TimelinePaginator.vue
- components/timeline/TimelinePublic.vue
- components/timeline/TimelinePublicLocal.vue
- pages/[[server]]/tags/[tag].vue
Currently main.elk.zone public timelines are broken when there is no user session due to change in #3273 😥
The fetch for "followed tags" need an authorized user session.
This PR will check for a user session before requesting "followed tags"
> fix: fetch for followed tags needs authorized session

- layouts/default.vue
- pages/[[server]]/index.vue
This will show the instance information (title, thumbnail, description) when there is no signed in user.
> feat: show server info on aside when not signed in

- app/composables/masto/icons.ts
Fixes #3309 by changing the unlisted post icon from lock to moon.
> fix: Proposal to use the "moon" icon for unlisted posts

- app/components/status/StatusBody.vue
- app/components/status/StatusTranslation.vue
- app/composables/masto/translate.ts
Currently, translations happen on the server by making a `POST` request to `https://translate.elk.zone/translate` as can be seen in Elk's production version and by inspecting the **Network** tab, filtering for `"translate"`:
This PR adds support for the experimental [Translation API](https://developer.chrome.com/docs/ai/translator-api) in Chrome, which consists of the Language Detector and the Translator API. These two APIa are currently in origin trials ([Translator API](https://developer.chrome.com/origintrials/#/view_trial/4445615782168100865), [Language Detector API](https://developer.chrome.com/origintrials/#/view_trial/662592095176884225)), so they can be tested already by real users.
The advantage over the current approach is reduced server costs for Elk, and full offline support, …
> feat: add support for the Translation API

- app/components/status/StatusCard.vue
- app/components/timeline/TimelinePaginator.vue
A post authored by the current user and displayed on someone else's profile page was incorrectly shown as a "pinned post," even though it wasn't actually pinned by the profile owner.
Added logic to check whether the account of the profile being viewed matches the account of the post.
This ensures that pinned posts are only shown on the author's own profile, and not on others' profiles.
This is my first pull request to this project, so I apologize in advance if I've missed any contribution guidelines.
> fix(profile): incorrect "pinned post" label shown on other account

- app/components/main/MainContent.vue
- app/components/nav/NavTitle.vue
Fixes #1836, which has links to the relevant WCAG success criterion, as well as Material Design guidelines and Apple HIG.
This small UI problem has been bothering me as an Elk user for a couple years. I still routinely miss clicks on the header's back button because its target area is so small. So here's a fix at last ^^
This PR:
- Increases the size of the sidebar (large screens) back button's target area from 30x22.5 to 45x45.
- Increases the size of the header (small & medium screens) back button's target area from 18x18 to 42.75x42.75.
- Sets a minimum height on the header, so that its height does not depend only on a combination of nested padding values and the presence or absence or specific buttons or content elements.
- Changes the buttons from `<a>` without a `href` (the result …
> fix(ui): increase target size of back button

- app/components/common/CommonScrollIntoView.vue
Current runs of ESLint on CI show a single warning, which shows up in an “Unchanged files with check annotations” in pull requests.
> /home/runner/work/elk/elk/app/components/common/CommonScrollIntoView.vue
> Warning:   3:3  warning  Prop "as" should be optional  vue/no-required-prop-with-default
https://github.com/elk-zone/elk/actions/runs/16146711224/job/45567384692?pr=3326#step:8:11
This PR fixes said warning, which limits noise in pull requests.
> chore: fix eslint warning for as prop

- server/utils/shared.ts
- helps users know which elk server(s) they have active login sessions with
- currently all login sessions are 'elk.zone'
- npm run dev
-  logged into my gotosocial server, inspected tokens under /settings/user/tokens, confirmed "App website" pointed to my local elk dev instance
> feat: pass origin as website when loging into server

- app/composables/content-parse.ts
- tests/nuxt/__snapshots__/content-rich.test.ts.snap
- tests/nuxt/content-rich.test.ts
Fix: Asterisk Rendering in Code Blocks
I've fixed the problem where pairs of asterisks were disappearing inside code blocks. My solution involves converting these asterisk pairs into HTML entities, which makes sure they now render correctly.
> fix(ui): Asterisk pairs are removed in code block

- README.md
From July 2023, Compose v1 stopped receiving updates. It’s also no longer available in new releases of Docker Desktop.
https://docs.docker.com/compose/releases/migrate/#how-do-i-switch-to-compose-v2
> docs: change docker compose command
